### ISSUE TITLE
Bug: Crash when select all and delete with only table in the editor

### ISSUE THREAD

**Issue by Shubhankerism** [facebook/lexical#6581] opened 2024-08-31 08:39 UTC
Copy-pasting/ Inserting a table into the editor and deleting it by selecting all crashes the editor.

Lexical version: v0.17.1

## Steps To Reproduce
1. By copy/paste
    - Copy a table
    - Ctrl + A in the lexical editor
    - Paste
    - Ctrl + A
    - Press Del key

![table-delete](https://github.com/user-attachments/assets/b6acac2c-995a-4947-86ef-ae9bd57d1af3)

2. By Inserting
    - Insert table
    - Remove everything before and after the table node
    - Ctrl + A
    - Press Del
    
![table-delete-2](https://github.com/user-attachments/assets/d29fbe8c-b21d-481b-bea0-7926f37afb1d)

## The current behavior
Can see crashes

## The expected behavior
To not crash and delete the table

**Comment by ivailop7** [comment] 2024-08-31 13:53
I've tried both ways, but I'm not able to reproduce those crashes, tried with both - the current playground and a few commits ago locally.

**Comment by Shubhankerism** [comment] 2024-09-01 02:28
Interesting - I can consistently reproduce the crash in the playground. After you inserted the table, did you remove the nodes before the table node?

**Comment by etrepum** [comment] 2024-09-01 15:17
The repro instructions for case 2 don't work for me, but it does work if there is nothing before and an empty paragraph after.

1. Clear editor
2. Insert table
3. Press up to move cursor to paragraph before table
4. Press delete to remove paragraph before table
5. Press Ctrl-A to select all
6. Press delete to crash

**Comment by etrepum** [comment] 2024-09-01 15:43
Appears to be a crash in `RangeSelection.getNodes` in `isBefore`. Could possibly be related to #6568 but the root cause is that by the time the `DELETE_CHARACTER_COMMAND` runs the table is already not connected (not sure yet what code is doing this) but since the DOM for it still exists it ends up getting selected along the way.

**Comment by etrepum** [comment] 2024-09-01 18:49
`$deleteCellHandler` is removing the table before the code runs. I think the root cause of the bug is really that `table.remove()` doesn't properly update the selection so it's likely the best fix is in `$removeNode` (perhaps `$maybeMoveChildrenSelectionToParent`)?

**Comment by etrepum** [comment] 2024-09-01 19:28
After doing a deeper dive it seems that the problem is that the implementation of `deleteCharacter` ends up applying the DOM selection to the current selection (via `applyDOMRange` in `modify`) after the node is already removed and chaos ensues because it ends up creating a selection where the anchor is not attached to the root anymore. It's a weird thing to do because at the point you call `applyDOMRange` the DOM and its selection might have no overlap at all with the document since reconciliation hasn't happened yet. Not exactly clear what the best fix would be, maybe @zurfyx has some insight because he has worked on some of this code (e.g. #3279).

In an ideal world I don't think we would want to call `applyDOMRange` in this flow at all, at least with the `character` granularity?

**Comment by etrepum** [comment] 2024-09-01 19:38
This is the playground URL I was using to repro the issue:

* [localhost](http://localhost:3000/#doc=H4sIAAAAAAAAE-3ZQWvCMBQH8O_yPwdpdaLLdbCz0OPYITZvtixryutTJ9LvPmorzB3EeRgy36mE5iWPX5r_pXuQLyVyJk4Idg-OUbpnXpTBM1WwL9cMXg18yZRLGSvYah2CwVvkDyewgEFZeaoENjGQXU2wqB27Fbu6gMGGuDkUpgZCn_I8VCb9MJNd6ErQ_n4bcctAOYXwY5uly99XHNeVf4oh8nGxPIasdv2Ugpyno9TEgON2eNeaO5ZIVUIlVOIiiSv74Lg9aeOc6H3xjvVDGyQSlVAJlbhIQmNYY1ivnEqohMbwf-LVGNYrpxIqoTGsMXwTEnrlVEIl_jaGr1znXJbf7Ekc_laeNN4aBNdI5jbkYdPZeDpOJvPp7PFhbtDENedd3SK4XX9S36uRjNLZKEX7BSs6FKAWHQAA)
* [playground](https://playground.lexical.dev/#doc=H4sIAAAAAAAAE-3ZQWvCMBQH8O_yPwdpdaLLdbCz0OPYITZvtixryutTJ9LvPmorzB3EeRgy36mE5iWPX5r_pXuQLyVyJk4Idg-OUbpnXpTBM1WwL9cMXg18yZRLGSvYah2CwVvkDyewgEFZeaoENjGQXU2wqB27Fbu6gMGGuDkUpgZCn_I8VCb9MJNd6ErQ_n4bcctAOYXwY5uly99XHNeVf4oh8nGxPIasdv2Ugpyno9TEgON2eNeaO5ZIVUIlVOIiiSv74Lg9aeOc6H3xjvVDGyQSlVAJlbhIQmNYY1ivnEqohMbwf-LVGNYrpxIqoTGsMXwTEnrlVEIl_jaGr1znXJbf7Ekc_laeNN4aBNdI5jbkYdPZeDpOJvPp7PFhbtDENedd3SK4XX9S36uRjNLZKEX7BSs6FKAWHQAA)

It doesn't preserve selection so you have to make the selection and then press delete but it makes setting it up a little quicker

**Closed** 2024-09-20 03:22 UTC
Labels: tables
