### ISSUE TITLE
Bug: backticks inside link title prevent Markdown rendering

### ISSUE THREAD

**Issue by vadimkantorov** [facebook/lexical#6337] opened 2024-06-25 15:12 UTC
```
- [relative/path/to/hello](relative/path/to/hello) : works
- [`relative/path/to/hello`](relative/path/to/hello) : does not render link
```

In GitHub both ways work:
- [relative/path/to/hello](relative/path/to/hello)
- [`relative/path/to/hello`](relative/path/to/hello)

![image](https://github.com/facebook/lexical/assets/1041752/3c564636-4c6f-49aa-8d10-871b4026a569)

![image](https://github.com/facebook/lexical/assets/1041752/5003d7b4-dd22-4622-a02d-6c3143a3d9cf)

It appears a Markdown parsing issue where the backticks-inside-link variant simply does not get parsed as a link

**Comment by vadimkantorov** [comment] 2024-06-27 13:54
Maybe the problem is in how https://github.com/facebook/lexical/blob/d13e5b893a2113d2df08c4d69e32cb8a355a8a23/packages/lexical-markdown/src/MarkdownTransformers.ts#L357 is implemented as a text match. Within the caption, some markdown should be parsed too or at least it should still get parsed as a link (even if some formatting from the caption is discarded).

**Comment by etrepum** [comment] 2024-09-23 14:36
Duplicate of #5148

**Closed by etrepum** 2024-09-23 14:36 UTC
