### ISSUE TITLE
Bug: flicker when select on popup

### ISSUE THREAD

**Issue by yaojiu19** [facebook/lexical#3950] opened 2023-02-22 07:42 UTC
Lexical version: 0.8.0

## Steps To Reproduce

![Feb-22-2023 15-41-31](https://user-images.githubusercontent.com/18085334/220554686-46ab6c2e-494e-4552-a72b-7d45ed24b1e0.gif)

**Comment by thegreatercurve** [comment] 2023-02-22 14:51
I think this might be a duplicate of #3727. The floating toolbar causes issues with the selection when you hover over it accidentally.

**Closed by thegreatercurve** 2023-02-22 14:51 UTC
