### ISSUE TITLE
Bug: Table is not deleted correctly when selected by shift + arrowup

### ISSUE THREAD

**Issue by 2wheeh** [facebook/lexical#5897] opened 2024-04-16 05:32 UTC
Lexical version: 0.14.3 (the latest)

## Steps To Reproduce

This one is separated from https://github.com/facebook/lexical/issues/5544#issuecomment-1953488420
and related with #5543

1. insert a table.
2. make it sure there is not next sibling paragraph node.
3. select the table by shift + arrowup.
4. delete by backspace key.
5. the issue happens in across browsers but same in safari and chrome and different in firefox probably due to different selection behavior.

Link to code example: can reproduce in playground

### in Safari and Chrome
- when there is prev sibling paragraph node and the last cell is empty

https://github.com/facebook/lexical/assets/40269597/42f5b411-9cfa-44fd-816c-332bbbc9e59d

- when there is prev sibling paragraph node and the last cell has textContent

https://github.com/facebook/lexical/assets/40269597/af352254-9409-4042-9f65-07833d00048b

- when there is not any prev silbing

https://github.com/facebook/lexical/assets/40269597/6de543d7-e562-4258-a5ae-37653babc545

### in Firefox
- when there is prev sibling paragraph node and the last cell is empty

https://github.com/facebook/lexical/assets/40269597/3db49ece-3ce2-47e4-902a-61c1d96d6869

- when there is prev sibling paragraph node and the last cell has textContent

https://github.com/facebook/lexical/assets/40269597/4597636b-8a1b-49ae-8e4e-132f91cb0995

- when there is not any prev silbing

https://github.com/facebook/lexical/assets/40269597/a825b73d-25c4-402c-a9ec-e9751beedba4

## The expected behavior

delete the table with its children whether there is any sibling or not.

**Comment by 2wheeh** [comment] 2024-04-16 05:46
@Sahejkm Would you confirm this is able to be replicated ?

**Comment by Sahejkm** [comment] 2024-04-16 09:43
> @Sahejkm Would you confirm this is able to be replicated ?

yea am able to replicate this.

**Comment by ivailop7** [comment] 2024-06-09 22:40
I wonder if the issue is the same as: https://github.com/facebook/lexical/pull/6274

**Comment by 2wheeh** [comment] 2024-06-10 01:30
> I wonder if the issue is the same as: https://github.com/facebook/lexical/pull/6274

@ivailop7 It seems more consistent but not resolved in #6274:


https://github.com/facebook/lexical/assets/40269597/620f0db7-ba36-4886-8581-d8b54c417814

**Comment by ivailop7** [comment] 2024-06-10 07:29
@serey-roth do you think we could have a generic solutiom for both Shift + Up and Shift + Down.

**Comment by ivailop7** [comment] 2024-06-10 21:40
> DELETE_CHARACTER_COMMAND

we already intercept the command for tables, so I agree it makes sense to modify the logic for tables

**Comment by ivailop7** [comment] 2024-06-10 21:41
> @ivailop7 I've found the bug in insertText. When we press backspace, `DELETE_CHARACTER_COMMAND` is triggered, which calls `selection.removeText`. The bug happens in `insertText` because it keeps the table and the last table row as the parent of the last node. This occurs in both "shift+arrow" scenarios.
> 
> https://www.loom.com/share/c2d7b4316a4445c9b26c0f840f2a5f1a?sid=526a7f79-34be-4b3c-a84a-84f4ae293dc2
> 
> I suggest we intercept this command and delete all nodes in the selection directly, avoiding the current command chain. What do you think?

Good find! We already handle that command in tables, so in my opinion it makes sense to fix it in there as well.

**Comment by serey-roth** [comment] 2024-06-12 22:45
> > @ivailop7 I've found the bug in insertText. When we press backspace, `DELETE_CHARACTER_COMMAND` is triggered, which calls `selection.removeText`. The bug happens in `insertText` because it keeps the table and the last table row as the parent of the last node. This occurs in both "shift+arrow" scenarios.
> > https://www.loom.com/share/c2d7b4316a4445c9b26c0f840f2a5f1a?sid=526a7f79-34be-4b3c-a84a-84f4ae293dc2
> > I suggest we intercept this command and delete all nodes in the selection directly, avoiding the current command chain. What do you think?
> 
> Good find! We already handle that command in tables, so in my opinion it makes sense to fix it in there as well.

@ivalop I think it made more sense to delete the table, if included in the selection, in `$deleteCellHandler`.

**Comment by ivailop7** [comment] 2024-06-12 22:47
Ok, I'll check the PR tomorrow. Thanks for looking into this.

**Comment by 2wheeh** [comment] 2024-06-13 13:42
@serey-roth 

#6274 fails to select whole table by "shift+arrowup" when their is no sibling at all, leading to fail to delete the table correctly.

https://github.com/facebook/lexical/assets/40269597/68283ff6-e120-4b6e-b4e2-42ea1de6487d

**Comment by serey-roth** [comment] 2024-06-13 20:57
> @serey-roth @ivailop7
> 
> #6274 fails to select whole table by "shift+arrowup" when their is no sibling at all, leading to fail to delete the table correctly.
> 
>  2024-06-13.10.10.16.mov


Thanks, @2wheeh, for catching this! I've updated #6274 to ensure a TableSelection occurs when you press "shift+arrowdown" into a table that is the first node.

Regarding the "shift+arrowup" bug @2wheeh found, I'm facing an inconsistency with the selection. When I "shift+arrowdown" into the first-node table, the focus sets on the paragraph node in the first cell. Ideally, it should be on the paragraph in the last cell, but instead, it's set on the root. This selection seems to come from the DOM, causing my recent change not to work since the selection isn't partially in the table.

https://www.loom.com/share/996b0660006042b598b9ebb8a73e9266?sid=ccdfbd83-47cd-4460-937d-8fc7dda39841

@2wheeh @ivailop7, I could add a check in the SELECTION_CHANGE_COMMAND listener in LexicalTableSelectionHelper where both the anchor and focus are on the root. However, I wanted to bring this up in case you have suggestions on a better approach.

**Comment by ivailop7** [comment] 2024-06-17 09:06
> > @serey-roth @ivailop7
> > #6274 fails to select whole table by "shift+arrowup" when their is no sibling at all, leading to fail to delete the table correctly.
> > 2024-06-13.10.10.16.mov
> 
> Thanks, @2wheeh, for catching this! I've updated #6274 to ensure a `TableSelection` occurs when you press "shift+arrowdown" into a table that is the first node.
> 
> Regarding the "shift+arrowup" bug @2wheeh found, I'm facing an inconsistency with the selection. When I "shift+arrowdown" into the first-node table, the focus sets on the paragraph node in the first cell. Ideally, it should be on the paragraph in the last cell, but instead, it's set on the root. This selection seems to come from the DOM, causing my recent change not to work since the selection isn't partially in the table.
> 
> https://www.loom.com/share/996b0660006042b598b9ebb8a73e9266?sid=ccdfbd83-47cd-4460-937d-8fc7dda39841
> 
> @2wheeh @ivailop7, I could add a check in the `SELECTION_CHANGE_COMMAND` listener in LexicalTableSelectionHelper where both the anchor and focus are on the root. However, I wanted to bring this up in case you have suggestions on a better approach.

This sounds reasonable, go for it. Is it only when it's root, or when embedded in any element node (collapsible, columns layout, etc) ?

**Comment by ivailop7** [comment] 2024-06-30 19:36
This is now fixed, it will be released with 0.16.1

**Closed by ivailop7** 2024-06-30 19:36 UTC
Labels: tables
