### ISSUE TITLE
Bug: Missing words and letters during editing. Video provided

### ISSUE THREAD

**Issue by ItsWuotan** [facebook/lexical#3889] opened 2023-02-12 10:17 UTC
https://user-images.githubusercontent.com/125186517/218304728-9515ea82-cbbe-4022-92d8-4f0d494dbed9.mp4

Lexical version: 0.8.0

## Steps To Reproduce

1. I used Brave Browser with Gboard on Android. 
2. As done in the video you can write yourself but it also happen when editing the default document

Link to code example:

## The current behavior
I think it's better explained in the screen recording but in short it deletes letters when backspace at the start of a line. It delete letters when double-tap space to punctuate. It also delete letters when backspace.

## The expected behavior
Not having letters and words be deleted during normal editing

**Comment by trueadm** [comment] 2023-02-13 10:36
Seems like a duplicate of https://github.com/facebook/lexical/issues/1973. Which unfortunately is a recent Android regression that we've flagged with Google.

**Closed by trueadm** 2023-02-13 10:36 UTC
Labels: high-pri
