### ISSUE TITLE
Bug: cannot find a LexicalComposerContext

### ISSUE THREAD

**Issue by ziedHamdi** [facebook/lexical#1892] opened 2022-04-20 10:23 UTC
Lexical version:
"lexical": "^0.2.1",

## Steps To Reproduce

1. Try to call const [editor] = useLexicalComposerContext();

Link to code example:

https://codesandbox.io/s/lexical-rich-text-example-forked-ivxcfi

## The current behavior
Unable to access the editor, don't know where I should create and provide a context if it has to be created (the file LexicalComposerContext doesn't provide a component to wrap the editor in) 

## The expected behavior
Reading the docs, https://jsrepos.com/repo/facebook-lexical it seems that is the way we can access the editor to register to its events and send it updates

**Comment by ziedHamdi** [comment] 2022-04-20 10:37
Actually I had to workaround it by adding a plugin that accesses the editor and send it to te parent:

function Editor(props) {

    const {contentEditable, placeHolder, editorReadyCallback} = props


    function EditorListenerPlugin(props) {
        const [editor] = useLexicalComposerContext();

        useEffect(() => {
                const unregisterListener = editor.registerUpdateListener(({editorState}) => {
                    // An update has occurred!
                    console.log(editorState);
                });
                editorReadyCallback(editor)
                return () => {
                    unregisterListener()
                }
            }
            ,
            [editor]
        )
        return null
    }

    return (
            <LexicalComposer initialConfig={editorConfig}>
                <div className="editor-container">
                    <ToolbarPlugin/>
                    <div className="editor-inner">
                        <RichTextPlugin
                            contentEditable={contentEditable}
                            placeholder={placeHolder ?? <Placeholder/>}
                        />
                        <EditorListenerPlugin/>
                    </div>
                </div>
            </LexicalComposer>
    );
}

**Comment by zurfyx** [comment] 2022-04-20 12:26
Yup, the workaround you found will work! That's because the editor is created on LexicalComposer, if you look at the source code it has a ContextProvider inside it.

That said, be careful when exporting the editor instance outside of it. It is hard to do this by design, LexicalComposer should always be the top most layer of edition, if you ever want to export something outside of it (i.e. save on the server) that should be via EditorState (`editor.addUpdateListener`)

**Comment by thegreatercurve** [comment] 2022-04-28 21:10
Closing this as it appears to be resolved.

**Closed by thegreatercurve** 2022-04-28 21:10 UTC

**Comment by trueadm** [comment] 2022-07-11 15:20
You need to use that hook within a LexicalComposer tree. If you don’t, it won’t work.

**Comment by CoenWarmer** [comment] 2022-07-12 04:04
Suggestion for improvement would be to include both the hook as well as the context required to use it in the documentation. I know Lexical is still in Alpha, so not a criticism per se, just a suggestion. It's not immediately obvious from the current state of the docs how this is supposed to work.
