### ISSUE TITLE
Bug: Additional break line when initializing or copy/pasting in the editor with break lines

### ISSUE THREAD

**Issue by ErPacheco** [facebook/lexical#3677] opened 2023-01-05 16:06 UTC
When I initialize the Lexical editor from an DOM like `<p><br></p>`, passing through `generateNodesFromDOM` and inserting the generated nodes to the editor, it imports it with an additional break line like `<p><br><br></p>`. This makes the editor have more break lines than expected. It is also curious that both <br> count as one character if I delete them and count the characters.

@zeitstein mentioned in a discord chat that when trying to pass a single `<p></p>` without break lines, it also imports it with an additional break line like `<p><br></p>`. They also mention that that this PR can be related -> https://github.com/facebook/lexical/pull/3581 (thanks for rising this up in the discord chat, here is the full thread: https://discord.com/channels/953974421008293909/1060331843578249376)

I also managed to reproduce it when copying some text with break lines from the Notes Application from my Mac.

Lexical version: 0.7.6

## Steps To Reproduce

1. Write something like this (with some break lines) in a Note in the Mac Notes Application:
```
First line



Fifth line
```
2. Copy the five lines (or the block of text you have written) and paste it in the lexical playground editor
3. You can find that there are more than 5 lines in this particular case.
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/26458400/210821038-a7e4d114-222c-4034-9cb5-5a73be0fb2d1.png">

-----------------

Here is an example of the InitialState plugin to initialize the editor from a preview HTML string (not sure why is duplicating the text in the codesandbox, in my code only runs once): https://codesandbox.io/s/break-line-example-w1ic2x?file=/src/plugins/InitialState.js

## The current behavior
When copying or initializing some text with break lines, it duplicates them, making the text different from the expected one.

## The expected behavior
When copying or initializing some text with break lines, the number of break lines is exactly the same as the one inserted in the editor.

**Comment by rabishah** [comment] 2023-01-13 16:13
I'm facing the same issue.

**Comment by chalecki** [comment] 2023-01-16 09:08
I'm facing the same issue. I've noticed `$generateNodesFromDOM` is adding an extra `<br />` tag for each "empty" paragraph. If you put any character, eg. period or even empty space - the problem does not exist

**Comment by rabishah** [comment] 2023-01-19 18:25
Facing the same issue, exactly as @chalecki .

**Comment by willwang888** [comment] 2023-01-20 00:09
Facing the same issue!

**Comment by chalecki** [comment] 2023-01-23 00:25
I think it was introduced in #590 in commit f38d4d52f24abc26d59c73989fc92c36fab19f8d . 

Commenting on this line https://github.com/facebook/lexical/blob/main/packages/lexical/src/LexicalReconciler.ts#L324 does the trick I think but I lack knowledge on the overall flow so would be best to hear from @trueadm more on this behavior

**Comment by almazkaliyev** [comment] 2023-01-23 15:34
maybe this can helps u

``` typescript
const removeLineBreaks = (inputHtml: string): string => {
  let copy = inputHtml
  copy = copy.replaceAll('<br>', '')
  return copy
}

const onChange = (_: EditorState, editorInstance: LexicalEditor) => {
  editorInstance.update(() => {
    const generatedHtml = $generateHtmlFromNodes(editorInstance, null)
    let resultHtmlString = wrapTables(generatedHtml)
    resultHtmlString = removeLineBreaks(generatedHtml)
    setHtml(resultHtmlString)
  })
}
```

**Comment by ErPacheco** [comment] 2023-01-24 22:30
@almazkaliyev the point is not to remove every `<br>` from the generated HTML, I want to keep the exact number of break lines from a copy/paste and when initialising the editor with some previous HTML saved from the database.

**Comment by sagarchoudhary96** [comment] 2023-02-22 07:56
@thegreatercurve  do we have any updates for the fix for this issue ?

**Comment by matttobrien** [comment] 2023-03-10 20:43
@thegreatercurve any updates? 😄

**Comment by oleksandr-danylchenko** [comment] 2023-03-15 09:07
Having the same issue. An empty text field has the `<p><br/></p` by default
|  Rich text field	|  `$generateHtmlFromNodes` result	|
|--------	|-------	|
|  ![image](https://user-images.githubusercontent.com/68850090/225260237-6cf3331d-b1e7-4bc0-ba3f-b791a269ba50.png)   	| ![image](https://user-images.githubusercontent.com/68850090/225260255-cc98d055-a3f6-49d3-ad1e-31d0835c9ae6.png)     	|

**Comment by keithhackbarth** [comment] 2023-04-25 23:57
@oleksandr-danylchenko and @ferugi - I am experiencing both of your observations reproducibly as well. 
@thegreatercurve - Let me know if anything we can do to help (ie test cases, repo steps, etc.)

**Comment by rjullian** [comment] 2023-05-09 16:54
I am experiencing a similar issue and would greatly appreciate any updates regarding the progress that has been made in resolving it. Thank you for your assistance.

**Comment by alexz-spotnana** [comment] 2023-05-12 16:04
This is my function to initialize the editor state from HTML. Since the lexical's renderer adds additional <br> tags, this function does the opposite – decreases the number of <br> tags by 1 in the parsed DOM and then parses DOM to nodes and inserts them into the editor.

```typescript
const parser = new DOMParser();
const dom = parser.parseFromString(initialHtml, 'text/html');

const elementsWithBr = dom.querySelectorAll('*:not(br) > br');
for (let i = 0; i < elementsWithBr.length; i += 1) {
  const brElement = elementsWithBr[i];
  const parentElement = brElement.parentNode;
  const lastBr = parentElement?.querySelectorAll('br:last-child')[0];
  if (lastBr === brElement) {
    parentElement?.removeChild(brElement);
  }
}

const nodes = $generateNodesFromDOM(editor, dom);

$getRoot().select();
$insertNodes(nodes);
```

**Closed** 2023-05-23 20:31 UTC
Labels: all-platforms-bug, html

**Comment by gajanan999** [comment] 2024-02-01 16:35
HI ,

I am facing this issue still in version 0.12.0

**Comment by rtrevisanlectra** [comment] 2024-02-28 18:05
Hello, same issue in version 0.13.1

**Comment by mustafamoe** [comment] 2024-03-10 10:37
Same issue in version 0.13.1

**Comment by Michael7141** [comment] 2024-04-11 10:01
> Hello, I'm having the same issue but found a workaround, if you clear the editor before the insertion, the line break is removed.
> 
> ```
> $getRoot().clear();
> $getRoot().select();
> $insertNodes(nodes);
> ```

bless your soul;
cuz u set mine on fire

**Comment by Talent30** [comment] 2024-06-12 03:46
> Hello, I'm having the same issue but found a workaround, if you clear the editor before the insertion, the line break is removed.
> 
> ```
> $getRoot().clear();
> $getRoot().select();
> $insertNodes(nodes);
> ```

Listen to this man and if you don't want the focus state after clear add. Please fix this Meta..

```
$setSelection(null);

```

**Comment by Pnlvfx** [comment] 2024-10-10 11:03
how is this bug still exist after 2 years?

**Comment by Dhruv97Sharma** [comment] 2024-10-30 11:11
Because the temporary fix to clear the editor (root) before selection works well, thanks @dpr10
