### ISSUE TITLE
Bug: new line character does not have any effect on editor

### ISSUE THREAD

**Issue by pranavmalvawala** [facebook/lexical#3651] opened 2022-12-28 09:34 UTC
Ideally when I put some empty lines in the editor, I want the empty lines to be shown in the preview. 

Specifically speaking, I'm converting state to markdown, saving it in database and then when I try to load it, the new lines (blank lines) that  I had created would not appear. 

Lexical version: 0.4.1

## Steps To Reproduce

1. Go this codesandbox 
2. type something and then leave some empty lines and then type again something
3. You'll see that the bottom editor doesn't show those spaces 

Link to code example: https://codesandbox.io/s/many-lexical-autofocus-bfqtmu?file=/package.json:226-231

## The current behavior
Empty lines won't show up

## The expected behavior
Empty lines should show up

**Comment by trueadm** [comment] 2023-01-03 12:02
Looks like an issue related to markdown? Also, please could you try updating Lexical to the latest version?

**Comment by fantactuka** [comment] 2023-04-08 01:19
Duplicate of #4271

**Closed by fantactuka** 2023-04-08 01:19 UTC
Labels: all-platforms-bug, markdown
