### ISSUE TITLE
Bug: Can't remove link formatting from links added by AutoLinkPlugin

### ISSUE THREAD

**Issue by andrewpashko** [facebook/lexical#5607] opened 2024-02-12 12:13 UTC
When link is typed manually and converted to link by AutoLink plugin
It is recognised as link but I cant remove link formatting when clicking on link format button

Lexical version: 0.13.1

## Steps To Reproduce

1. Type link "www.customlink.com"
2. Select link for editing with FloatingLinkToolbar
3. Click on link formatting button

https://github.com/facebook/lexical/assets/23315851/6b7e63e9-6993-4373-8693-c107058922f5

## The current behavior
Link formatting isn't removed

## The expected behavior
Link formatting is removed

**Comment by ivailop7** [comment] 2024-02-17 16:18
Well, that's kind of 'working as designed', since the AutoLinkPlugin is a node transform that's run on every editor update, in this case any string that matches www.... will be picked up as a link, so even after 'removing' the link, the text is still picked up by the AutoLink node transform, since it's an editor update action, so this works as expected. To achieve the behaviour you want, you would need to extend the AutoLink plugin and introduce some type of memory on 'unlink' that after running the regex, if the regex match is in the set of 'unlinked' urls to be skipped. This is oversimplified, since if you have the same link twice in the text it would apply to the second instance of the link text, but you get the point. If you want to tackle and contribute back to the playground, the addition would be welcome.

**Comment by larrygotto** [comment] 2024-04-02 11:37
@ivailop7 why should this be 'working as designed'? If the user wants to remove the link, the editor behavior should be to remove it. I don't see no reason for the intended behavior not to be part of AutoLinkPlugin as default.

**Comment by larrygotto** [comment] 2024-04-02 11:38
I'll be closing the issue #5806 since this one is the same. But I still thing this should be the default for AutoLinkPlugin

**Comment by ivailop7** [comment] 2024-04-02 11:43
The working as designed part was referring to transformers. The ability to unlink an autolink makes sense to be added in an efficient way.

**Comment by StyleT** [comment] 2024-04-05 22:41
I don't see any reason here why `AutoLinkNode` can't have "unlinked" state here. When it is shown as a regular text

**Comment by larrygotto** [comment] 2024-04-05 22:47
Sounds good!!

**Closed** 2024-06-19 13:34 UTC
Labels: good first issue, contribution-week
