### ISSUE TITLE
Bug: AutoFocusPlugin does not work with markdown. 

### ISSUE THREAD

**Issue by rmosias2** [facebook/lexical#5709] opened 2024-03-13 21:21 UTC
`AutoFocusPlugin` seems to only work with Plain Text; when added with markdown, it ends up getting lost. This may happen because plain text is added with just one <p> tag, whereas markdown text involves several wrapped HTML tags.

Lexical version: 0.13.1

## Steps To Reproduce

1. Create Text with markdown such #
2. Add `<AutoFocusPlugin defaultSelection="rootStart" />`

Link to code example:
https://codesandbox.io/p/live/94dfdc00-94da-4c25-9d5a-9bad7627698c

## The current behavior

![Screenshot 2024-03-13 at 18 16 13](https://github.com/facebook/lexical/assets/86744969/66fa0108-b692-47f6-ba31-b1716b9f5340)

## The expected behavior 
![Screenshot 2024-03-13 at 18 20 31](https://github.com/facebook/lexical/assets/86744969/365b3f40-ca09-4301-b55a-a605fd8df466)

**Comment by etrepum** [comment] 2024-12-10 19:30
This is because `$convertFromMarkdownString` creates a selection. Duplicate of #6323

**Closed by etrepum** 2024-12-10 19:30 UTC
