### ISSUE TITLE
Bug: Two lists should merge when list node become next to another list

### ISSUE THREAD

**Issue by willwang888** [facebook/lexical#3781] opened 2023-01-25 20:51 UTC
If list A and list B are siblings separated by a paragraph P, where list B comes after P, backspacing at the start of P does not merge Lists A and B. List B should merge into list A. Currently, they are separate.

Discord conversation about this: https://discordapp.com/channels/953974421008293909/955972012541628456/1067907284254072902

Lexical version: Playground, 0.76

## Steps To Reproduce

1. Create a list A with two list item nodes
2. Separate them with a paragraph node so the configuration is List A -> P -> List B.
3. Backspace at the start of the paragraph node.
4. Observe the editor state as List A -> List B. There should only be one list, List A.

## The current behavior
https://user-images.githubusercontent.com/13092862/214687684-06869331-f662-455a-bb27-bdbadcf6eff1.mov

**Comment by thegreatercurve** [comment] 2023-01-26 10:05
Closing this as a duplicate of #3433, which is currently still open. We should fix this soon with a refactor of the lists logic.

**Closed by thegreatercurve** 2023-01-26 10:05 UTC
