### ISSUE TITLE
Bug: Cannot insert image to new inserted table row in playground

### ISSUE THREAD

**Issue by tducloc** [facebook/lexical#5408] opened 2023-12-21 08:35 UTC
Lexical version: 0.12.5

## Steps To Reproduce

1. Insert a table
2. Insert a new row
3. Insert a image on new row

Link to code example:

## The current behavior
- Console show error

https://github.com/facebook/lexical/assets/72237443/4d8d89c5-8882-4bda-81f0-9f3e13ecec8a

## The expected behavior
- Should be able to insert image into table

**Comment by tducloc** [comment] 2023-12-21 09:05
By now, I temporarily fixed this by getting new inserted table row then loop through its cell and add the empty paragraph

`
const insertTableRowAtSelection = useCallback(
    (shouldInsertAfter: boolean) => {
      editor.update(() => {
        $insertTableRow__EXPERIMENTAL(shouldInsertAfter);

        // get inserted table row node
        const tableNode = $getTableNodeFromLexicalNodeOrThrow(tableCellNode);
        const tableRows = tableNode.getChildren();
        const tableRowIndex = shouldInsertAfter ? tableRows.length - 1 : 0;
        const tableRow = tableRows[tableRowIndex];

        // Loop through table row and insert empty paragraph nodes
        const tableCells = tableRow.getChildren();
        for (let i = 0; i < tableCells.length; i++) {
          const tableCell = tableCells[i];

          if (!$isTableCellNode(tableCell)) {
            throw new Error('Expected table cell');
          }

          tableCell.append($createParagraphNode());
        }

        clearTableSelection();
        onClose();
      });
    },
    [clearTableSelection, editor, onClose, tableCellNode]
  );
`

**Comment by thorn0** [comment] 2023-12-22 22:29
Duplicate of https://github.com/facebook/lexical/issues/5286

**Comment by ivailop7** [comment] 2024-05-21 22:14
The fix for this issue seems to be in #5912

**Comment by ivailop7** [comment] 2024-06-09 22:45
This works now. Closing.

**Closed by ivailop7** 2024-06-09 22:45 UTC
Labels: tables
