### ISSUE TITLE
Bug: Markdown export should escape literal asterisks

### ISSUE THREAD

**Issue by robfig** [facebook/lexical#4808] opened 2023-07-21 13:08 UTC
Lexical version: 0.11.3

## Steps To Reproduce

1. Write some text that includes asterisks
2. Export to markdown using default settings
3. Render markdown to HTML using remarkjs or any other CommonMark-compliant markdown renderer

**Actual result:** emphasis is applied, treating the literal asterisks as markup
**Expected result:** the export of un-formatted text nodes should escape asterisks and underscores. Exported markdown, when rendered, should resemble what the user saw in Lexical

Lexical already provides a markdown-as-you-type capability to apply formatting (which can be undone with Ctrl-Z), so I don't think that the current behavior could be desirable. The relevant change would be simple & made in `exportTextFormat`.

We noticed this trying to write math:
1. Wrote this text: `a*1.5 + b*.15`
2. Output this markdown: `a*1.5 + b*.15`
3. Rendered to HTML: `<p>a<em>1.5 + b</em>.15</p>`

Here is a quick script to demonstrate

```javascript
import { CodeNode } from "@lexical/code";
import { createHeadlessEditor } from "@lexical/headless";
import {
  AutoLinkNode,
  LinkNode
} from "@lexical/link";
import { ListItemNode, ListNode } from "@lexical/list";
import { $convertToMarkdownString, TRANSFORMERS } from "@lexical/markdown";
import { HeadingNode, QuoteNode } from "@lexical/rich-text";
import {
  $createParagraphNode, $getRoot,
  $getSelection, TextNode
} from "lexical";
import { micromark } from "micromark";
import { gfm, gfmHtml } from 'micromark-extension-gfm';


export const editorConfig = {
  namespace: "x",
  nodes: [
    HeadingNode,
    ListNode,
    ListItemNode,
    QuoteNode,
    CodeNode,
    AutoLinkNode,
    LinkNode,
    TextNode,
  ],
};

const editor = createHeadlessEditor(editorConfig);
editor.update(() => {
  const root = $getRoot();
  const paragraph = $createParagraphNode();
  root.append(paragraph);
  paragraph.select();
  $getSelection()?.insertText(`a*1.5 + b*.15`)
  const md = $convertToMarkdownString(TRANSFORMERS);
  console.log(md)
  console.log(micromark(md, {
    extensions: [gfm()],
    htmlExtensions: [gfmHtml()]
  }));
})
```

**Comment by cduff** [comment] 2024-11-06 04:40
Related to https://github.com/facebook/lexical/issues/2715?

**Comment by etrepum** [comment] 2024-12-10 18:53
Duplicate of #2715

**Closed** 2024-12-10 18:54 UTC
Labels: markdown
