### ISSUE TITLE
Bug: Select all in copy pasted table broken

### ISSUE THREAD

**Issue by potatowagon** [facebook/lexical#5987] opened 2024-04-29 17:01 UTC
Lexical version:

## Steps To Reproduce

1. copy this html table

First Header | Second Header
-- | --
Content Cell | Content Cell
Content Cell | Content Cell

2. paste into lexical
3. add some text above the table
4. select all (use keyboard shortcut)
5. notice the selection in debug tree view is only midway, not all selected
6. press backspace, only some cells get deleted. expected -> whole table get deleted
7. repeat this enough and the editor freezes

## The current behavior

https://github.com/facebook/lexical/assets/19604232/3c46aa9b-8e1b-4fe8-aaf3-c87d273da3cb

https://github.com/facebook/lexical/assets/19604232/e6274cce-f00e-498b-8eee-91a672f0437a

^ clue: notice how i can repro the incomplete selection if i dont drag my mouse all the way to the right to select all. if i drag all the way, i can select the remaining nodes in tree view

## The expected behavior

all selected, all deleted. Not reproducible with table that is created in lexical, only happens for pasted table.

**Comment by vect-spasquereau** [comment] 2024-06-24 15:40
@potatowagon I can also reproduce with tables created with lexical 👀

https://www.loom.com/share/4c7a197e8079402193c6783b3b85979b

**Comment by ivailop7** [comment] 2024-06-30 19:44
@vect-spasquereau and @potatowagon could you recheck if you can still repro, we merge a shift+arrow up/down selection fix which I think fixed this, I couldn't repro it anymore, but would be nice if either of you can confirm if it's fixed now.

**Comment by vect-spasquereau** [comment] 2024-07-02 12:38
@ivailop7 it seems to be fixed indeed, cannot reproduce 🙂

**Closed** 2024-07-03 13:00 UTC
Labels: tables

**Comment by potatowagon** [comment] 2024-07-08 06:59
same here, thanks @ivailop7 for the fix!
