### ISSUE TITLE
Bug: Backspace on beginning of paragraph following an image deletes it instead of merging

### ISSUE THREAD

**Issue by KararTY** [facebook/lexical#6987] opened 2024-12-21 00:48 UTC
Lexical version: Playground (0.21.0)

## Steps To Reproduce

1. Add sample image.
2. Add text "abc" after image on same row/paragraph.
3. Move to beginning of "abc", press Enter to create new row/paragraph.
4. Press Backspace. 

Link to code example: https://playground.lexical.dev/

## The current behavior
Backspace on beginning of paragraph following an image deletes the image.

https://github.com/user-attachments/assets/8dc62a08-1405-441f-b2a0-d7ca8e91c701

## The expected behavior
On document editors like Google Docs, the text "abc" will be placed alongside the image instead of the image being deleted.

https://github.com/user-attachments/assets/1956e5d8-8362-4910-b198-49b03e4a550b

## Impact of fix
This is just an inconsistency vs how Google Docs & LibreOffice works. Haven't tested others.

**Comment by etrepum** [comment] 2024-12-21 16:58
Pretty sure this is a duplicate of #6974

**Closed** 2024-12-21 16:58 UTC
Labels: decorators
