### ISSUE TITLE
Bug: Exported command identity is unstable

### ISSUE THREAD

**Issue by focux** [facebook/lexical#3661] opened 2022-12-30 22:42 UTC
I'm trying to implement dragging and dropping images using the `DRAG_DROP_PASTE` command that is exported from the `@lexical/rich-text` package. I created a plugin similar to the `DragDropPaste` that is on the Lexical playground and the callback that I registered is never called when I drop or paste an image.

After long hours debugging this issue, I find out that the object identity of the exported `DRAG_DROP_PASTE` is not stable, so when an image is dropped or pasted, the dispatched `DRAG_DROP_PASTE` command identity does not match the registered command one, even though it should be the same. I'm not sure if it's because I'm using Next.js 13, with server components, however, the editor is a client component.

To workaround this bug, I patched the library and made `DRAG_DROP_PASTE` a string instead of `createCommand('DRAG_DROP_PASTE')` and it's working fine.

Lexical version: 0.7.5

## Steps To Reproduce

1. Create a new project using Next.js 13
2. Create a new rich editor
3. Copy and paste the `DragDropPaste` plugin from the Lexical playground. You can swipe the callback of the `DRAG_DROP_PASTE` command and console log instead. 
4. Drop an image and see that the command's callback isn't called.

Link to code example:

## The current behavior

The callback of the `DRAG_DROP_PASTE` is not called.

## The expected behavior

The callback of the `DRAG_DROP_PASTE` should work.

**Comment by trueadm** [comment] 2023-01-03 11:13
The command `DRAG_DROP_PASTE` is most definitely stable. It's an object and this is intentional. If you are having issues with it not working, it could be that you're bundling multiple versions of Lexical or the plugins – resulting in different copies of `DRAG_DROP_PASTE`. Have you checked your bundle?

**Comment by thegreatercurve** [comment] 2023-01-17 10:39
Closing this as the issue is unclear. The command object literals are stable otherwise.

**Closed by thegreatercurve** 2023-01-17 10:39 UTC

**Comment by Yhuley** [comment] 2024-05-13 09:46
I have the same issue. It looks like `DRAG_DROP_PASTE` doesn't happen on image drop since I don't see any logs in console. Here is the example of my editor implementation:

`editor.tsx`
```typescript
const Editor = () => (
  <LexicalComposer initialConfig={initialConfig}>
      <RichTextPlugin
        placeholder={<Placeholder />}
        ErrorBoundary={LexicalErrorBoundary}
        contentEditable={<ContentEditable />}
      />
      <ImageDropPastePlugin />
  </LexicalComposer>
);
``` 

`image-drop-paste-plugin.ts`

```typescript
const ImageDropPlugin = () => {
  useImageDrop();

  return null;
};
``` 

`use-image-drop-paste.ts`

```typescript
import { useLexicalComposerContext } from '@lexical/react/LexicalComposerContext';
import { DRAG_DROP_PASTE } from '@lexical/rich-text';
import { COMMAND_PRIORITY_LOW } from 'lexical';
import { useEffect } from 'react';

const useImageDropPaste = () => {
  const [editor] = useLexicalComposerContext();

  useEffect(
    () =>
      editor.registerCommand(
        DRAG_DROP_PASTE,
        (files) => {
          console.log('files', files);
          return true;
        },
        COMMAND_PRIORITY_LOW,
      ),
    [editor],
  );
};
``` 

Have I missed anything important?

cc @trueadm @thegreatercurve @focux

**Comment by davidng10** [comment] 2025-01-11 13:39
@Yhuley check your package versions, i faced this issue recently, my lexical/react + lexical package was 0.22 whereas the lexical/rich-text was 0.23.1. Resolving all 3 packages to the same version solved my issue.
