### ISSUE TITLE
Bug: Table issue when merging multiple rows

### ISSUE THREAD

**Issue by PeterBul** [facebook/lexical#4872] opened 2023-08-09 10:15 UTC
The editor crashes when merging cells spanning two or more full rows.

This is due to $forEachGridCell expecting all rows to exist, which is not the case if two whole rows are merged.

Lexical version: 0.11.3

1. Add a table with i.e. 5 rows and columns
2. Mark all cells spanning two full rows.
3. Merge cells using the table cell action menu
4. It crashes

https://github.com/facebook/lexical/assets/23295934/5204883b-6a8f-4d08-99b5-25f1094ec026

Link to code example:
https://playground.lexical.dev/
The bug exists in the playground

## The current behavior
It crashes. It continues to crash when trying to select cells, so table cell selection is also broken at this point.
## The expected behavior
It should not crash and table cell selection should continue to work.

**Comment by PeterBul** [comment] 2023-08-09 11:44
getCordsFromCellNode in TableNode throws an error if a row is not found. Is it preferable that non-existing rows due to merge are still represented by an empty array, or should the throwing of errors be removed?

Ensuring that array indices are never removed seems like a more tedious and fragile fix than just accepting undefined rows. 
Undefined rows and columns can be type-checked by changing Cells to:
```ts
export type Cells = Array<Array<Cell | undefined> | undefined>;
```

Another option would be to slice the array instead of just removing the index. This would lead to indices not matching with the underlying table structure, which would probably lead to too much refactoring and thus seems like a worse option.

**Comment by elbotho** [comment] 2024-08-19 22:09
I believe this is fixed with https://github.com/facebook/lexical/pull/4874.

**Comment by etrepum** [comment] 2024-08-22 18:18
Unable to reproduce, it does appear that this has been fixed!

**Closed by etrepum** 2024-08-22 18:18 UTC
Labels: tables
