### ISSUE TITLE
Bug: How to save Lexical Editor content from Yjs in a NestJS backend?

### ISSUE THREAD

**Issue by FirasLatrech** [facebook/lexical#6700] opened 2024-10-04 15:10 UTC
Hi everyone,

I’m working on a project using the Lexical editor for rich text editing, Yjs for real-time collaboration, and a NestJS backend. I’m currently facing a challenge with saving the editor content. Specifically, I need to extract the content from the Yjs messages and store it in my backend.

I’m unsure how to properly retrieve the Lexical editor's content from Yjs and send it to the backend for persistence. Has anyone worked with this combination or has any insights on how to achieve this?

Any help or code examples would be greatly appreciated! Thanks in advance!

**Comment by moy2010** [comment] 2024-10-04 17:25
This is not a bug. Use the discord channel for asking questions.

**Comment by etrepum** [comment] 2024-10-04 17:46
Closing as this is not a bug.

**Closed by etrepum** 2024-10-04 17:46 UTC
