### ISSUE TITLE
Bug: formatting block over-reaches into sibling block

### ISSUE THREAD

**Issue by zeeyang** [facebook/lexical#3066] opened 2022-09-24 16:26 UTC
Lexical version: 0.5.0 and prior

## Steps To Reproduce

1. select paragraph with **triple click** (key is to use triple click so line break is included in selection)
2. change block formatting from toolbar

![Kapture 2022-09-24 at 09 25 31](https://user-images.githubusercontent.com/2062827/192108597-ac11080c-f5d4-4db1-ae51-b9ed9f86c21b.gif)

## The current behavior
Formatting is applied to current selected block and next sibling block

## The expected behavior
`$wrapNodes` should exclude next unselected sibling

**Comment by EgonBolton** [comment] 2022-12-20 22:37
I consider this a duplicate of https://github.com/facebook/lexical/issues/2648

**Comment by mattslight** [comment] 2023-01-18 23:09
Issue is still present in 0.7.5 and 0.7.6 in playground

**Comment by mattslight** [comment] 2023-01-18 23:10
<img width="1311" alt="Screenshot 2023-01-18 at 6 47 02 PM" src="https://user-images.githubusercontent.com/1073639/213315235-520ce54e-37f2-4e9b-9e04-9d6d7766288f.png">
<img width="1116" alt="Screenshot 2023-01-18 at 6 50 21 PM" src="https://user-images.githubusercontent.com/1073639/213315254-cdadb3cc-072f-4195-a5f2-1f5099207213.png">
https://user-images.githubusercontent.com/1073639/213315278-4db0563c-7b38-47bf-9d63-6304e1fb0b4c.mp4

**Comment by thegreatercurve** [comment] 2023-03-21 09:55
Closing as a duplicate of #2648

**Closed by thegreatercurve** 2023-03-21 09:55 UTC
