### ISSUE TITLE
Bug: IOS mobile safari cursor position problem

### ISSUE THREAD

**Issue by sliyoxn** [facebook/lexical#6537] opened 2024-08-21 04:27 UTC
In the mobile IOS system, the cursor behind the DecoratorNode node seems to be forced to move to the beginning of the paragraph, making it impossible to focus the cursor behind the DecoratorNode node

Lexical version: newest

## Steps To Reproduce

1. open [playground](https://playground.lexical.dev/)  in ios safari
2. add some text
3. insert an image node
4. input some text

## The current behavior

video here: 

https://github.com/user-attachments/assets/a439cc0f-8d1c-431a-a78e-94e60e1c27f2

## The expected behavior

the cursor can show behind DecoratorNode like mac safari

## Impact of fix

Ensure consistent experience across all ends

**Comment by etrepum** [comment] 2024-08-23 23:27
This looks like a duplicate of #4487

**Closed by etrepum** 2024-08-23 23:27 UTC
