### ISSUE TITLE
Bug: Importing from markdown does not respect escaping

### ISSUE THREAD

**Issue by robfig** [facebook/lexical#4844] opened 2023-07-28 17:31 UTC
## Steps To Reproduce

1. Enter `\*Hello\*` here to see that it is valid markdown which is rendered as expected: https://spec.commonmark.org/dingus/
2. Go to lexical playground, clear the content, switch to Markdown mode. Enter `\*Hello\*`
3. Click the markdown button to import. 

Expected: It populates the WYSIWYG editor with the literal text `*Hello*`

Actual: It displays _\\Hello\\_

This is because it ignores the escaping and treats the surrounding asterisks as a format to be applied. The process of applying the text formats should do a negative lookbehind assertion to confirm that the previous character is not a backslash.

Before import
![image](https://github.com/facebook/lexical/assets/536325/0d919b0a-f973-4c2e-9331-c42c17fce9ac)

After import
![image](https://github.com/facebook/lexical/assets/536325/8d705482-d5dd-4cf2-9139-c4cf28d73bd4)

**Comment by robfig** [comment] 2023-07-28 17:42
Oh interesting, `createTextFormatTransformersIndex` does indeed add a negative lookbehind for escaping. I'm not sure why it's not working at this point.

**Comment by robfig** [comment] 2023-07-28 18:12
OK, it's the switch here that adds the negative assertion depending on userAgent. It turns out my Jest test is classified as IS_APPLE_WEBKIT, although I think it should support the regexp. 

So maybe the fix is to change the condition under which it's not used? 

```
    if (IS_SAFARI || IS_IOS || IS_APPLE_WEBKIT) {
      fullMatchRegExpByTag[tag] = new RegExp(
        `(${tagRegExp})(?![${tagRegExp}\\s])(.*?[^${tagRegExp}\\s])${tagRegExp}(?!${tagRegExp})`
      );
    } else {
      fullMatchRegExpByTag[tag] = new RegExp(
        `(?<![\\\\${tagRegExp}])(${tagRegExp})((\\\\${tagRegExp})?.*?[^${tagRegExp}\\s](\\\\${tagRegExp})?)((?<!\\\\)|(?<=\\\\\\\\))(${tagRegExp})(?![\\\\${tagRegExp}])`
      );
    }

```

**Comment by ratasorin** [comment] 2023-07-29 15:27
Hello, I created a pull request that fixes this issue and #4808, you can see if it fits your requirements here: #4813

**Comment by antsorin** [comment] 2024-02-26 14:59
Hi everyone.

Any update on this?
Note that at the moment, neither import nor export handle the text content escaping, making the markdown support less reliable for production use.

Will @ratasorin's code be reviewed and hopefully merged soon?

**Comment by cduff** [comment] 2024-11-06 04:41
Duplicate of https://github.com/facebook/lexical/issues/2715?

**Comment by etrepum** [comment] 2024-12-10 18:54
Duplicate of #2715

**Closed by etrepum** 2024-12-10 18:54 UTC
