### ISSUE TITLE
Bug: Excalidraw editor does not close on remote collaborator editor

### ISSUE THREAD

**Issue by echarles** [facebook/lexical#2788] opened 2022-08-08 12:41 UTC
Lexical version: 0.3.8

## Steps To Reproduce

1. Run lexical in collaborative mode in the playground
2. Create an excalidraw in editor 1 and save it

## The current behavior

The drawing is shown in editor 2, but the excalidraw component does not close.

## The expected behavior

The excalidraw comonent should close and editor 2 should have the content created by editor 1.

![Untitled5](https://user-images.githubusercontent.com/226720/183420360-494e170b-d7d4-46ef-8424-b1197471ec8f.gif)

**Comment by thegreatercurve** [comment] 2022-11-24 15:50
Duplicate of #1788

**Closed by thegreatercurve** 2022-11-24 15:50 UTC
Labels: good first issue
