### ISSUE TITLE
Bug: Writing an url using AutoLinkPlugin is not working for endings with ".co.uk"

### ISSUE THREAD

**Issue by larrygotto** [facebook/lexical#5802] opened 2024-04-02 00:27 UTC
When using the AutoLinkPlugin with the provided matchers, urls like `www.test.co.uk` are auto added, but stop at the second `.`
Trying to use different Regex matchers end up with the same results.

Lexical version: The current version on Playground

## Steps To Reproduce

1. Just start writing any url on the playground

## The current behavior

https://github.com/facebook/lexical/assets/92735047/5e8b67e1-a55a-48f5-b64f-e8108219e302

## The expected behavior
The link keeps adding after the second `.`

**Comment by 2wheeh** [comment] 2024-04-02 00:41
Duplicate of #4692

**Comment by thegreatercurve** [comment] 2024-04-02 09:24
Closing as duplicate of above.

**Closed by thegreatercurve** 2024-04-02 09:24 UTC
