### ISSUE TITLE
Bug: Copy Pase of List elements b/w Playground & any Custom Instance is producing extra lines

### ISSUE THREAD

**Issue by gaurav21r** [facebook/lexical#3740] opened 2023-01-17 13:57 UTC
**Since this bug pertains to a base level feature (Lists & Clipboard) I'm flagging as URGENT**

Lexical version: 0.6.0 to latest

## Steps To Reproduce

1. Make a list of any arbitrary depth in the playground https://playground.lexical.dev/
<img width="783" alt="image" src="https://user-images.githubusercontent.com/1716462/212914315-04747033-3a3f-4615-8236-5255bbe51053.png">

2. Copy paste this list (along with the heading & any other element(s) ) in any arbitrary custom instance of Lexical. For example, the *Rich Text* sandbox in the website https://lexical.dev itself, will give this:

<img width="458" alt="image" src="https://user-images.githubusercontent.com/1716462/212914782-04ea89b2-c314-4114-aac9-26978faf056d.png">

Link to code example: Codesandbox link of Rich Text Editor from the website itself: https://codesandbox.io/s/lexical-rich-text-example-5tncvy?from-embed

## The current behavior
There is an extra `\n` being added to every list item that has a sub list.

## The expected behavior
The playground editor and all other editors should behave consistently.

## Probable cause.
I couldn't understand the code much but I think this line may be the offender.
https://github.com/facebook/lexical/blob/68c64e942967e86238760858af259117fa9a8c7c/packages/lexical-clipboard/src/clipboard.ts#L126

<img width="614" alt="image" src="https://user-images.githubusercontent.com/1716462/212917454-bf9df20b-2c70-43ce-be6c-2f5277d119df.png">

The comment seems to suggest something to the issue.

**Comment by bschwartz10** [comment] 2023-01-19 17:16
Experiencing the same behavior of the insertion of an empty `editor-listitem` when parsing html content back into the editor

**parsing logic**
```
const root = $getRoot()
const parser = new DOMParser()
const dom = parser.parseFromString(value, 'text/html')
const nodes = $generateNodesFromDOM(editor, dom)         
root.append(...nodes)
```

**rendered text**
<img width="717" alt="Screen Shot 2023-01-19 at 11 58 56 AM" src="https://user-images.githubusercontent.com/21000661/213513192-16732ca7-fd73-4a79-87d1-7498eb60754d.png">

**Lexical editor w/ extra empty `editor-listitem`**
<img width="723" alt="Screen Shot 2023-01-19 at 11 58 41 AM" src="https://user-images.githubusercontent.com/21000661/213513190-10ba1a6c-3487-4e84-9a82-1e7ec213485d.png">

**HTML Output**
```
<ol class="editor-list-ol">
    <li value="1" class="editor-listitem ltr" dir="ltr"><span data-lexical-text="true">It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s</span></li>
    <li value="2" class="editor-listitem ltr" dir="ltr"><span data-lexical-text="true">It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s</span></li>
    <li value="3" class="editor-listitem"><br></li>
// ^Extra editor-listitem
    <li value="4" class="editor-listitem editor-nested-listitem">
        <ol class="editor-list-ol">
            <li value="1" class="editor-listitem ltr" dir="ltr"><span data-lexical-text="true">Hows it going</span></li>
        </ol>
    </li>
</ol>
```

**Comment by gaurav21r** [comment] 2023-01-20 11:21
@trueadm @thegreatercurve As I mentioned should be easy to reproduce for you from the playground website and the lexical homepage. Please give some direction, whenever free.

**Comment by thegreatercurve** [comment] 2023-01-20 11:43
@gaurav21r I think the issue is more to do with the list logic, which we're looking to refactor in the next couple of months. It's a long standing issue with how we are nesting lists #2951

**Comment by gaurav21r** [comment] 2023-01-20 12:10
@thegreatercurve Thanks for responding! Yes it does seem to be the long term fix for this issue. But can you suggest a temp workaround till then? 

What I find intriguing is that if I copy the list in the playground and paste it (even in a separate playground instance) its working, similarly if I copy it from the CodeSandbox on the home page and paste it there only its working. Its only when its being transferred across each other that this bug happens. Maybe there is a Plugin in the Playground that's contributing to this?

**Comment by acywatson** [comment] 2023-01-20 14:32
> @thegreatercurve Thanks for responding! Yes it does seem to be the long term fix for this issue. But can you suggest a temp workaround till then?

What I find intriguing is that if I copy the list in the playground and paste it (even in a separate playground instance) its working, similarly if I copy it from the CodeSandbox on the home page and paste it there only its working. Its only when its being transferred across each other that this bug happens. Maybe there is a Plugin in the Playground that's contributing to this?

This behavior is most likely because the bug you're seeing is with HTML Serialization. Lexical uses native JSON transfer format for most cases between Lexical instances, so the bug occurs when the paste content is HTML, but not when it's JSON.

**Comment by acywatson** [comment] 2023-01-20 14:32
> > @thegreatercurve Thanks for responding! Yes it does seem to be the long term fix for this issue. But can you suggest a >temp workaround till then?
> 
> What I find intriguing is that if I copy the list in the playground and paste it (even in a separate playground instance) its >working, similarly if I copy it from the CodeSandbox on the home page and paste it there only its working. Its only when its >being transferred across each other that this bug happens. Maybe there is a Plugin in the Playground that's contributing to >this?
> 
> This behavior is most likely because the bug you're seeing is with HTML Serialization. Lexical uses native JSON transfer >format for most cases between Lexical instances, so the bug occurs when the paste content is HTML, but not when it's >JSON.

**Comment by gaurav21r** [comment] 2023-01-21 10:24
@acywatson Thanks a ton! Let me Pull master and confirm so we can close this!

**Comment by chalecki** [comment] 2023-01-23 01:57
Thanks a lot @acywatson 🍺 !

**Comment by EgonBolton** [comment] 2023-01-23 16:18
> I think the issue is more to do with the list logic, which we're looking to refactor in the next couple of months

hey @thegreatercurve or anyone else on the team. This information is critical to me. Could you tell me what the change will consist of please?

**Comment by acywatson** [comment] 2023-01-23 16:50
> Could

https://github.com/facebook/lexical/issues/2951#issuecomment-1364156496

Most of the context is in this thread that you’re already involved in. There’s not much else. @thegreatercurve will own this

**Closed** 2023-02-09 21:30 UTC
