### ISSUE TITLE
Bug: Some URL's with subdomains fail with AutoLinkPlugin

### ISSUE THREAD

**Issue by prestonbrown-me** [facebook/lexical#3560] opened 2022-12-15 13:00 UTC
Some URLs will fail in the autolinkplugin regardless of the matcher used.

Lexical version: 0.7.1

## Steps To Reproduce
1. type URL with subdomain such as `https://about.meta.com` into the playground: https://playground.lexical.dev
2. URLs with subdomains do work in some cases, such as `https://playground.lexical.dev`

## The current behavior
different length subdomains fail to autolink in playground example

**Comment by thegreatercurve** [comment] 2022-12-16 18:28
Duplicate of #3546

**Closed by thegreatercurve** 2022-12-16 18:28 UTC
