### ISSUE TITLE
Bug: TypeError: $isGridSelection is not a function

### ISSUE THREAD

**Issue by fyepi** [facebook/lexical#5454] opened 2024-01-06 11:34 UTC
Lexical version:
0.12.5

I have tried to extract the official lexical playground package from lexical mono repo and make it an independent package, with published lexical packages as dependencies. I intend to build a custom editor based on it.

I got this error:

`TypeError: $isGridSelection is not a function`

The link to the repo is: 

https://github.com/fyepi/lexical-playground

![image](https://github.com/facebook/lexical/assets/153042320/6915a132-2075-4d8a-a6f4-2c0044a6e072)

I use `node v18.17.0`, `pnpm 8.6.9` and `vite 5.0.0`.

**Comment by khanakia** [comment] 2024-01-06 11:57
Duplicate of https://github.com/facebook/lexical/issues/5411

**Comment by ivailop7** [comment] 2024-01-19 23:27
I believe this is now fixed as 0.12.6, could you confirm?

**Closed** 2024-01-20 14:10 UTC

**Comment by fyepi** [comment] 2024-01-23 06:24
Yes.It has been fixed. Thanks @ivailop7
