### ISSUE TITLE
Bug: AutoLink doesn't replace URLs containing multiple periods

### ISSUE THREAD

**Issue by redstar504** [facebook/lexical#5768] opened 2024-03-26 21:36 UTC
Lexical version:

## Steps To Reproduce

1.  Go to the [playground](https://playground.lexical.dev/)
2.  Type in a URL containing more than one period (ie. http://www.example.com)

Link to code example:

[Screencast from 2024-03-26 02:26:04 PM.webm](https://github.com/facebook/lexical/assets/1311325/4763ca18-9781-4d25-bcc5-113d3d9633b0)

## The current behavior

Only the portion of the URL up to the second period is replaced by the AutoLink plugin.

## The expected behavior

The entire string should be replaced with a link.

**Comment by ivailop7** [comment] 2024-03-26 21:57
Duplicate of #4692

**Closed by ivailop7** 2024-03-26 21:57 UTC
