### ISSUE TITLE
Feature: Links support formatted text in markdown format

### ISSUE THREAD

**Issue by KingSora** [facebook/lexical#3764] opened 2023-01-23 08:38 UTC
Currently if I want to have a link with different formatting in markdown format its not possible as the resulting markdown simply erases the formatting. And example would be:

If I write: 
```
[This is a **bold** text](url)
```
It becomes:
```
[This is a bold text](url)
```

After some digging I've found the [LINK markdown transformer](https://github.com/facebook/lexical/blob/main/packages/lexical-markdown/src/MarkdownTransformers.ts#L321), where I've found [this comment](https://github.com/facebook/lexical/blob/main/packages/lexical-markdown/src/MarkdownTransformers.ts#L329-L330) in the export functon:

> Add text styles only if link has single text node inside. If it's more
> then one we ignore it as markdown does not support nested styles for links

Which I found to be invalid, since markdown indeed supports nested styles for links: [This is a **bold** text](url)

So I've changed the export function of the LINK transformer to return all formatted nodes like this:
```js
{
  export: (node, exportChildren) => {
    if (!$isLinkNode(node)) {
      return null;
    }
    const linkContent = `[${exportChildren(node)}](${node.getURL()})`;
    return linkContent;
  },
}
```
Which gives me the desired output. The only problem is that importing is not possible anymore because the link isn't recognized as a link anymore if it has formatted text inside. It seems that its not the fault of the LINK transformer but rather of how all the transformers are working together.

I've created a working example here: https://codesandbox.io/s/blue-surf-gttxnh?file=/src/plugins/MarkdownTransformers.ts
Steps to test:
- select part of the string and make it bold
- click on the "convert markdown" button in the bottom right corner
- observe if the link text has the correct markdown format
- click the "convert markdown" button again
- the link is not a link anymore, instead its just text with correct bold format

If I could get hints what exactly to change / try out I would be ready to create PR for this.

**Comment by etrepum** [comment] 2024-09-23 14:37
Duplicate of #5148

**Closed by etrepum** 2024-09-23 14:37 UTC
Labels: all-platforms-bug, markdown
