### ISSUE TITLE
Bug: broken formatting when using strikethrough and inline code in markdown

### ISSUE THREAD

**Issue by olafsulich** [facebook/lexical#6945] opened 2024-12-12 07:04 UTC
Lexical version:

v0.21.0

## Steps To Reproduce

Type "hello world", select it, and convert it to inline code. Then, select "hello", and make it strikethrough:

![image](https://github.com/user-attachments/assets/d2abaaef-dbde-4b0b-8bb7-c98b1371085e)
 
Convert to markdown string.

You'll get:

![image](https://github.com/user-attachments/assets/eae22336-9d13-48a2-96b3-ef8d9b0f5bcf)

## The current behavior

The result is "~~`hello~~ world`", which prevents it from being correctly styled.

## The expected behavior

I'd expect the result to be different. Maybe "`~~hello~~ world`" or "`~~hello~~` `world`" (two code blocks)? I'm not sure, I leave it to you to judge :)

## Impact of fix

It's not very common, but it breaks the formatting and can happen in everyday use.

**Comment by etrepum** [comment] 2024-12-16 01:25
This looks like a duplicate of #2303

**Closed by etrepum** 2024-12-16 01:25 UTC
