### ISSUE TITLE
Bug: table can't be copied when only table is present

### ISSUE THREAD

**Issue by mrdivyansh** [facebook/lexical#6438] opened 2024-07-22 04:10 UTC
Lexical version: 0.16.1

A table doesn't get copied to the clipboard when there is only one table as content.

## Steps To Reproduce

1. Visit https://playground.lexical.dev/
2. Insert a table using the `Insert` dropdown.
3. Delete the paragraph nodes, above and below the table.
4. Press `Cmd+A` to select the table.
5. Press `Cmd+C` to copy the table.
6. Press `Backspace` to delete the table.
7. Press `Cmd+V` to trigger the paste action.

Expected: I should see a table on the editor.
Actual: I see random text pasted from the clipboard that I had copied before.

https://github.com/user-attachments/assets/9c0e1447-2fb2-428a-a478-6b08927e0fbd

**Comment by etrepum** [comment] 2024-12-02 05:44
I can't reproduce this, probably fixed by one of the recent table refactors such as #6889

**Closed by etrepum** 2024-12-02 05:44 UTC
