### ISSUE TITLE
Bug: Backspace in Firefox duplicates entire line

### ISSUE THREAD

**Issue by AlessioGr** [facebook/lexical#5233] opened 2023-11-15 20:51 UTC
https://github.com/facebook/lexical/assets/70709113/50e4b047-ff90-4b2e-9e63-1fc9a52477e8

This only happens in Firefox. It does not happen in Chrome. I'm on macOS.

**To reproduce:**
1. Create multi-line paragraph
2. Select last word in the paragraph
3. Press backspace

Original issue (from lexical editor used in payload): https://github.com/payloadcms/payload/issues/3928

**Comment by patricsgamma** [comment] 2024-01-22 10:46
Found this issue originally in Payload's implementation, now also in Lattice an HR software that is also using lexical editor.
Would love to see some movement on it, so not every customer support is just recommending chrome as default to solve any browser related problem ;)

**Comment by kalgynirae** [comment] 2024-03-06 17:49
Just in case it's useful, I've found several slightly different methods for reproducing this:

**Common setup for all methods below**
1. Use Firefox
2. Type "This is a test"
3. Press Shift+Enter (to enter a linebreak in the current paragraph)

**Up/Down arrow key method**
1. Position the cursor at the end of the first line
2. Press Down, Up (so that the cursor is once again positioned at the end of the first line, but you got there via an Up arrow keypress)
3. Press Backspace
--> See the text "his is a test" appear after the cursor

**Double-click selection method**
1. Double-click on the word "test" to select it
2. Press Backspace
--> See the text "his is a test" appear after the cursor

**Ctrl+Shift+Right arrow selection method**
1. Position the cursor just before the word "test"
2. Press Ctrl+Shift+Right (macOS: Option+Shift+Right) to select the whole word "test"
--> See the text "his is a test" appear after the cursor

**Ctrl+Delete method**
1. Position the cursor just before the word "test"
2. Press Ctrl+Delete (macOS: Option+Fn+Backspace) to delete the whole word "test"
--> See the text "his is a test" appear after the cursor

The common pattern in all of these methods seems to be that the cursor jumps to the position immediately before the linebreak via some "unusual" method.

**Comment by agriffis** [comment] 2024-04-02 20:57
I'm confused! The fix for this was merged, then reverted. The bug still reproduces on the playground. Should this issue be reopened?

**Closed** 2024-04-24 22:13 UTC
