### ISSUE TITLE
Bug: Decorator nodes block hotkey movements

### ISSUE THREAD

**Issue by WesleyKapow** [facebook/lexical#5680] opened 2024-03-03 18:13 UTC
Lexical version: 0.13.1

Related: https://github.com/sodenn/lexical-beautiful-mentions/issues/382

## Steps To Reproduce
1. Setup text between two decorator nodes
2. Position cursor in-between the two decorator nodes.
3. Hit Control-A and Control-E
4. Observe cursor is blocked by the decorator nodes instead of moving to front/end of the line

## The current behavior
![309551893-bd98d957-0ce1-42df-9dd1-336f2240727a](https://github.com/facebook/lexical/assets/1568246/c342452f-2d0e-46a5-9d78-3a3f029342e9)

## The expected behavior
Decorator nodes have no impact on normal keyboard shortcuts for text editing.

> Control-A: Move to the beginning of the line or paragraph.
> Control-E: Move to the end of a line or paragraph.
> Source: https://support.apple.com/en-us/HT201236

**Comment by thegreatercurve** [comment] 2024-04-02 11:50
Closing this as it seems to be a bug with Chromium. Here is an existing relevant bug report: https://issues.chromium.org/issues/41484126

For reference, the reason this shortcut doesn't work as intended is that we set `contenteditable="false"` on the inline decorator nodes. 

I've checked in the playground and this works correctly on Firefox as in the bug mentioned above.

**Closed by thegreatercurve** 2024-04-02 11:50 UTC
