### ISSUE TITLE
Bug: caret jumping to the beginning after Node Transforms

### ISSUE THREAD

**Issue by tilxyz** [facebook/lexical#5757] opened 2024-03-22 18:44 UTC
Not entirely sure if this is a bug or just me not knowing the right way to do things. 

I'm trying to support emoji in my lexical editor. Followed some example in the playground repo, got it working, but ran into an issue that: after the new emoji node replaces the text, the caret jumps back to the beginning, see the screen recording. 

https://github.com/facebook/lexical/assets/142543453/8df8c543-3abc-4f53-85a3-1770c037a983

Here's the relevant emoji plugin code:
```
function textNodeTransform(node: TextNode): void {
    if (!node.isSimpleText() || node.hasFormat('code')) {
        return;
    }

    const text = node.getTextContent();
    // Find only 1st occurrence as transform will be re-run anyway for the rest
    // because newly inserted nodes are considered to be dirty
    const emojiMatch = findEmoji(text);
    if (emojiMatch === null) {
        return;
    }

    let targetNode;
    if (emojiMatch.position === 0) {
        // First text chunk within string, splitting into 2 parts
        [targetNode] = node.splitText(
            emojiMatch.position + emojiMatch.shortcode.length,
        );
    } else {
        // In the middle of a string
        [targetNode] = node.splitText(
            emojiMatch.position,
            emojiMatch.position + emojiMatch.shortcode.length,
        );
    }
    if (targetNode) {
        const emojiNode = $createEmojiNode(emojiMatch.unifiedID);
        targetNode.replace(emojiNode);
    }
}

function useEmojis(editor: LexicalEditor): void {
    useEffect(() => {
        if (!editor.hasNodes([EmojiNode])) {
            throw new Error('EmojisPlugin: EmojiNode not registered on editor');
        }

        return editor.registerNodeTransform(TextNode, textNodeTransform);
    }, [editor]);
}

export default function EmojiPlugin(): JSX.Element | null {
    const [editor] = useLexicalComposerContext();
    useEmojis(editor);
    return null;
}
``` 

Lexical version: 0.13.1

## Steps To Reproduce

1. type something like "abcd :smile :"
2.see the caret jumps back to the beginning 

## The current behavior
see the caret jumps back to the beginning after inserting an emoji

## The expected behavior
The caret should be after the emoji.

**Comment by ivailop7** [comment] 2024-03-22 19:57
I'm not able to reproduce in the playground. The caret remains after the inserted emoji

**Comment by thegreatercurve** [comment] 2024-04-02 13:47
Closing as I can't repro this either in the playground.

**Closed by thegreatercurve** 2024-04-02 13:47 UTC
