### ISSUE TITLE
Feature: Editor within Custom Element Shadow DOM

### ISSUE THREAD

**Issue by johnstonmatt** [facebook/lexical#4870] opened 2023-08-09 04:11 UTC
I would like to be able to instantiate a lexical editor bound to an element within a Shadow DOM. When lexical is configured in this way it fails to properly process updates to that element's contents. I believe that the project has a huge opportunity here, _maybe_ even something like a `<lexical-composer>` custom element, bringing the vanilla DX closer to React's.

I am happy to implement my own editor as a user as well of course, but that requires a fix for processing updates to the editor element contents in a ShadowRoot.

**Comment by StyleT** [comment] 2024-04-05 22:58
Hi!
Can you provide some code sandbox (e.g. fork https://stackblitz.com/github/facebook/lexical/tree/main/examples/vanilla-js?file=src%2Fmain.ts) with an example of the issue?

**Comment by adrian-bobev** [comment] 2024-05-31 20:21
> Hi! Can you provide some code sandbox (e.g. fork https://stackblitz.com/github/facebook/lexical/tree/main/examples/vanilla-js?file=src%2Fmain.ts) with an example of the issue?
> 
> If you do, it will help a lot with resolution ;)

@StyleT, I also have the same problem. If the contenteditable div is placed inside shadowRoot the editor does not work. If the div is in the light dom, everything is working as expected.

I suppose the problem is that getSelection is not working in shadowRoot.

Here is isolated example of the problem:
https://stackblitz.com/edit/vitejs-vite-ardtzj?file=src%2Fmy-element.ts

**Comment by abishek-srinivasan** [comment] 2024-08-08 13:18
Hello @StyleT @adrian-bobev @johnstonmatt . I have been facing the same issue. Did we have a chance to find some workaround for this or any idea on whether this issue was fixed in recent versions of lexical?

**Comment by adrian-bobev** [comment] 2024-08-08 18:42
@abishek-srinivasan The only workaround that I found is to place the contenteditable div inside the light DOM

**Comment by etrepum** [comment] 2024-12-03 06:30
I don't think that shadow dom selections are supported well enough cross-platform for this to be feasible. See also #6709 and #2119

**Closed by etrepum** 2024-12-03 06:30 UTC
Labels: enhancement

**Comment by aleksandr-konovalov** [comment] 2026-02-04 10:58
https://github.com/facebook/lexical/pull/7790

Here's the solution. We had a long discussion about this pull request, but it died down. We'll wait for a response from the respected maintainers.
