### ISSUE TITLE
Bug: Press Enter in numpad doesn't trigger registerCommand(KEY_ENTER_COMMAND)

### ISSUE THREAD

**Issue by tranducck** [facebook/lexical#6176] opened 2024-05-27 06:48 UTC
Lexical version: 0.15.0

## Steps To Reproduce

1. 
2.

Link to code example:

**Comment by potatowagon** [comment] 2024-05-29 09:23
im not able to reproduce this issue


https://github.com/facebook/lexical/assets/19604232/3636e520-3786-40f8-85c7-b87e90ec76bd

**Comment by potatowagon** [comment] 2024-05-29 09:24
closing since issue is incomplete and over a day old, do reopen if i misunderstood the issue

**Closed by potatowagon** 2024-05-29 09:24 UTC

**Comment by tranducck** [comment] 2024-05-30 01:57
Hi, I make a simple test. I put a console.log inside registerCommand(KEY_ENTER_COMMAND) callback and it doesn't fire when I press NumPadEnter. You can see in images below.
You can test again by my github repo: https://github.com/tranducck/lexical-test
![2024-05-30_08-52](https://github.com/facebook/lexical/assets/19758694/e85bf7a1-6111-4ab1-b91d-c391285736d2)
![2024-05-30_08-50](https://github.com/facebook/lexical/assets/19758694/202f8efd-3ddc-4ff4-8751-adce2ac33d57)

**Comment by tranducck** [comment] 2024-06-03 04:38
@potatowagon any update?

**Comment by potatowagon** [comment] 2024-06-03 05:16
> @potatowagon any update?

what is the impact of this issue? any example user flows this is breaking? also please complete the issue form

**Comment by thanhpk** [comment] 2024-06-04 16:27
hi @potatowagon  We use lexical editor to build a chat application. When the user types a message and then presses `Enter`, the application should send the message. We rely on `KEY_ENTER_COMMAND` to do this.

Everything worked fine until I upgraded to lexical version *0.15.5*, the application did not send the message when the user pressed the numpad-enter key but instead inserted a newline character. Investigating more closely, I found that lexical does not send `KEY_ENTER_COMMAND` when the numpad-enter key is pressed.

I think you should reopen the issue

**Comment by potatowagon** [comment] 2024-06-05 08:37
https://github.com/facebook/lexical/assets/19604232/ce5295b4-6b30-4872-ae18-337da66ebadb

^ numpad enter triggers KEY_ENTER_COMMAND

https://github.com/facebook/lexical/pull/6110 published 3 weeks ago  also has a demo where numpad enter sends the message.

perhaps try upgrading to [v0.16.0](https://github.com/facebook/lexical/releases/tag/v0.16.0) and see if that fixes your issue

**Comment by tranducck** [comment] 2024-06-05 09:25
Thanks.
I have tested that v0.16.0 fixed this issue
