### ISSUE TITLE
Feature: Convert selection to markdown

### ISSUE THREAD

**Issue by jovan-actdigital** [facebook/lexical#6908] opened 2024-12-04 15:34 UTC
## Description
I want to when I select some text in editor retrieve that text with markdown styling, but only thing I was able to retrieve is plain text with $getSelection().getTextContent().

My question: Is there a way to retrieve markdown when selecting text from editor?

**Comment by etrepum** [comment] 2024-12-10 18:56
Duplicate of #6503

**Closed by etrepum** 2024-12-10 18:56 UTC
Labels: enhancement
