### ISSUE TITLE
Bug: Editor is not able to import superscript and subscript styling from html string

### ISSUE THREAD

**Issue by Rajatava** [facebook/lexical#3452] opened 2022-11-29 13:26 UTC
Lexical version: 0.6.3

**issue with importing superscript styling** 

![lexical-superscript1](https://user-images.githubusercontent.com/49876019/204538756-3be2bb02-0ca1-44f0-a864-069880108340.png)

$generateHtmlFromNodes() yields the following html string 

`<p class="PlaygroundEditorTheme__paragraph"><span>10</span><sup><span class="PlaygroundEditorTheme__textSuperscript">12</span></sup></p>`

But When we try to populate the same html string to the editor using $generateNodesFromDOM() method, this results the following 

![Lexical-superscript2](https://user-images.githubusercontent.com/49876019/204538957-ba71c079-18c2-44f8-9d66-107633c94a49.png)

**issue with importing subscript styling** 

![lexical-subscript-1](https://user-images.githubusercontent.com/49876019/204539265-b1cf571b-2b8d-4e51-923c-0c38a3b87ac7.png)

$generateHtmlFromNodes() yields the following html string 

`<p class="PlaygroundEditorTheme__paragraph" dir="ltr"><span>log</span><sub><span class="PlaygroundEditorTheme__textSubscript">2</span></sub><span>10</span></p>`

But When we try to populate the same html string to the editor using $generateNodesFromDOM() method, this results the following 

![lexical-subscript2](https://user-images.githubusercontent.com/49876019/204539424-254baf62-8304-4a8e-a15a-1987d9d65787.png)

So, Editor is not able to regenerate subscript and superscript styling from the html string.

**Comment by thegreatercurve** [comment] 2022-11-29 13:40
Duplicate of #2202.

**Closed by thegreatercurve** 2022-11-29 13:40 UTC
