### ISSUE TITLE
Bug: having extremely hard time converting html -> lexical    parsing html  keeps adding in... repeating initial html.  $generateNodesFromDom doesn't apply all styles.  

### ISSUE THREAD

**Issue by thegirlyoucallryan** [facebook/lexical#3760] opened 2023-01-20 18:45 UTC
![Screen Shot 2023-01-20 at 1 43 03 PM (2)](https://user-images.githubusercontent.com/67074772/213780715-43c06b93-391c-43e3-8d61-2031ef8923b9.png)

```
<img width="1728" alt="Screen Shot 2023-01-20 at 1 43 03 PM" src="https://user-images.githubusercontent.com/67074772/213780977-c778415e-c8e7-4ea2-b93a-6d023ee89877.png">


export function Editor(placeholder: string) {
  function SerializeHtmlPlugin(placeh

older: string) {
    const [editor] = useLexicalComposerContext()

    useEffect(() => {
      return editor.update(() => {
        const parse = new DOMParser()
        const text = parse.parseFromString(placeholder, 'text/html')
        const nodes = $generateNodesFromDOM(editor, text)
        const root = $getRoot()

        nodes.forEach((node, i) => {
          if ($isElementNode(node) || $isDecoratorNode(node)) {
            root.append(node)
          }
        })
      })
    }, [editor, placeholder])
    return null
  }

  const editorConfig = {
    // The editor theme

    theme: ExampleTheme,
    editorState: SerializeHtmlPlugin,
    // Handling of errors during update
    onError(error: any) {
      throw error
    },
    // Any custom nodes go here
    nodes: [
      HeadingNode,
      ListNode,
      ListItemNode,
      QuoteNode,
      CodeNode,
      CodeHighlightNode,
      TableNode,
      TableCellNode,
      TableRowNode,
      AutoLinkNode,
      LinkNode,
    ],
  }

  return (
    <div className="App">
      <LexicalComposer initialConfig={editorConfig}>
        <div className="editor-container">
          <ToolbarPlugin />
          <div className="editor-inner">
            <RichTextPlugin
              contentEditable={<ContentEditable className="editor-input" />}
              placeholder={<Placeholder placeholder={placeholder} />}
              ErrorBoundary={LexicalErrorBoundary}
            />

            <HistoryPlugin />
            <AutoFocusPlugin />
            <AutoLinkPlugin />
            <ListPlugin />
            <LinkPlugin />
            <OnChangePlugin onChange={(state) => console.log(state)} />
          </div>
        </div>
      </LexicalComposer>
    </div>
  )
}

```

**Comment by Birddle** [comment] 2023-01-24 00:59
Why would you pass Placeholder perhaps you want to implement the initialized load content function?

**Comment by acywatson** [comment] 2023-01-25 22:46
Closing this because there's not enough information to reproduce a specific issue.

**Closed by acywatson** 2023-01-25 22:46 UTC
