### ISSUE TITLE
Bug: Automatic links are incomplete.

### ISSUE THREAD

**Issue by arayutw** [facebook/lexical#4027] opened 2023-03-04 13:27 UTC
If more than one dot is included, only the middle of the dot will be linked.

Please refer to the image.

<img width="203" alt="スクリーンショット 2023-03-04 22 25 28" src="https://user-images.githubusercontent.com/125749298/222904438-7fd5c9aa-cfa8-42d8-865b-79a3dd14013c.png">

**Comment by thegreatercurve** [comment] 2023-03-06 09:59
Duplicate of #3546

**Closed by thegreatercurve** 2023-03-06 09:59 UTC
