### ISSUE TITLE
Remove root listeners

### ISSUE THREAD

**Issue by thegreatercurve** [facebook/lexical#1589] opened 2022-04-01 14:30 UTC
From @trueadm  in #1503:

> I really don't feel they push folks down the path of success. They encourage adding listeners to the contenteditable, but really they should probably be delegating events to the document and, where possible, leveraging commands instead.

**Comment by zurfyx** [comment] 2022-06-14 12:47
Duplicate of #1311

**Closed by zurfyx** 2022-06-14 12:47 UTC
Labels: enhancement
