### ISSUE TITLE
Bug: Lexical Conversion to markdown conversion and vice versa not working properly for multiple combination of Bold, Italic and strikethrough with space seperated

### ISSUE THREAD

**Issue by prasadpendke** [facebook/lexical#7009] opened 2024-12-31 13:33 UTC
Lexical version: 0.20.0

## Steps To Reproduce

1. https://playground.lexical.dev/
2. Click on bold -> Write "Test" -> Provide space -> Click on Italic -> Write "Text"
3. Click in markdown converter
4. Click on lexical view 
5. Text will be distorted and unable to parse converted markdown in lexical 

Link to code example:

## The current behavior
![image](https://github.com/user-attachments/assets/175570b1-d8b3-44c2-b3ba-48f8c48b2d48)
![image](https://github.com/user-attachments/assets/1156a6ce-6809-46f2-9dae-ced061145667)
![image](https://github.com/user-attachments/assets/5bdc1b0f-4283-4f09-b7df-15187ac47423)

## The expected behavior
After conversion from markdown to lexical, it should be like below and value should be intact and same as before 
![image](https://github.com/user-attachments/assets/175570b1-d8b3-44c2-b3ba-48f8c48b2d48)

## Impact of fix
We have started using this library for our critical application but lexical library is not working for basic operations mentioned above which is not expected. Can you please try to fix this issue asap as users already started complaining about this issue in production?

**Comment by etrepum** [comment] 2024-12-31 16:53
I think this is a duplicate of #7009

**Closed by etrepum** 2024-12-31 16:53 UTC

**Comment by prasadpendke** [comment] 2025-01-01 09:53
@etrepum may as you have mentioned, this issue is duplicate of https://github.com/facebook/lexical/issues/4895 but may I know when can we get a fix for this issue as that issue is **already open from past 1.5 years** and it is very crucial for our application.

**Comment by etrepum** [comment] 2025-01-01 13:46
It will get fixed when somebody motivated to do so submits a PR with tests that fixes it and doesn't break anything else. If it's crucial to your application, maybe you should give it a go, or find a way to incentivize someone else to do it for you.
