### ISSUE TITLE
Lexical github:Links: Double click to edit link not standard not discoverable "enough"

### ISSUE THREAD

**Issue by kraisler** [facebook/lexical#1147] opened 2022-01-20 23:45 UTC
I do think the drag+select to invoke the popup is very nice!  Keep that, but please handle single click.
https://user-images.githubusercontent.com/1952520/150439839-c8c18047-fc80-4e08-9bcc-bcce19569adc.mov

**Comment by thegreatercurve** [comment] 2022-11-24 11:58
Closing as its a duplicate of #1795.

**Closed by thegreatercurve** 2022-11-24 11:58 UTC
Labels: all-platforms-bug, hyperlinks
