### ISSUE TITLE
Bug: [Playground] autolink escapes on second `.` when typing

### ISSUE THREAD

**Issue by zeitstein** [facebook/lexical#3546] opened 2022-12-13 10:39 UTC
## Steps To Reproduce

Type in e.g. `https://www.foo.com` in Playground. Works as expected on paste.

## The current behavior

![image](https://user-images.githubusercontent.com/8146007/207295726-ef2b50a6-5d84-4385-805f-6aed8b1a2477.png)

**Comment by prestonbrown-me** [comment] 2022-12-16 23:57
some urls with subdomains do actually work. for example, typing `https://playground.lexical.dev` does work. I believe this has to do with the autolink plugin itself, rather than the URL matcher used.

**Comment by NikolajLeischner** [comment] 2023-01-10 09:51
I ran into the same issue and could track it to this change: https://github.com/facebook/lexical/commit/f29ab08dbf9c0b14b89ebef44fa243e712d817ad#diff-d62fd402ee470b9082046b4a435f031dd8539650efc92ac2ea645f8ded2a4c57R55

If you remove the "." from the `PUNCTUATION_OR_SPACE` regex, then the issue disappears.

**Comment by thegreatercurve** [comment] 2023-02-03 11:57
I'm not sure there's much we can do here. This is technically behaving correctly. 

The regex is accounting for valid URLs which omit their subdomains (i.e. `https://github.com`), but it doesn't make any distinction when such a URL uses "www" as it's actual domain. 

This is technically valid behaviour. Sites like `https://www.org` are a valid, and we want them to be recognised by the regex.

**Comment by NikolajLeischner** [comment] 2023-02-13 09:01
Closing this doesn't seem very helpful. As is, the autolink-plugin is useless. It doesn't recognize most URLs with sub-domains correctly, and no URLs if you add a protocol. And this is independent of the regex you provide the plugin with.

**Comment by acywatson** [comment] 2023-02-17 17:07
> Closing this doesn't seem very helpful. As is, the autolink-plugin is useless. It doesn't recognize most URLs with sub-domains correctly, and no URLs if you add a protocol.
Note that this behavior is independent of the matchers you provide the plugin with.

Agreed, this was closed prematurely, I think. We need to see what we can do to fix this.

**Comment by Karibash** [comment] 2023-02-18 14:25
> I ran into the same issue and could track it to this change: [f29ab08#diff-d62fd402ee470b9082046b4a435f031dd8539650efc92ac2ea645f8ded2a4c57R55](https://github.com/facebook/lexical/commit/f29ab08dbf9c0b14b89ebef44fa243e712d817ad#diff-d62fd402ee470b9082046b4a435f031dd8539650efc92ac2ea645f8ded2a4c57R55)
> 
> If you remove the "." from the `PUNCTUATION_OR_SPACE` regex, then the issue disappears.

If the "." is removed from the regex, the following string will also be recognized as a URL, so it is necessary to consider another modification method.
`https://github.com...`

**Comment by NikolajLeischner** [comment] 2023-03-16 13:04
> > I ran into the same issue and could track it to this change: [f29ab08#diff-d62fd402ee470b9082046b4a435f031dd8539650efc92ac2ea645f8ded2a4c57R55](https://github.com/facebook/lexical/commit/f29ab08dbf9c0b14b89ebef44fa243e712d817ad#diff-d62fd402ee470b9082046b4a435f031dd8539650efc92ac2ea645f8ded2a4c57R55)
> > If you remove the "." from the `PUNCTUATION_OR_SPACE` regex, then the issue disappears.
> 
> If the "." is removed from the regex, the following string will also be recognized as a URL, so it is necessary to consider another modification method. `https://github.com...`

Gotcha, I didn't test that case.. :)

**Comment by NozomiSugiyama** [comment] 2023-04-30 07:57
It seems that the issue with https://github.com/... being allowed might be due to a problem with the URL REGEX in packages/lexical-playground/src/plugins/AutoLinkPlugin/index.tsx:
```javascript
/((https?:\/\/(www\.)?)|(www\.))[-a-zA-Z0-9@:%._+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_+.~#?&//=]*)/.test("https://github.com...")
> true
```

Additionally, having the "." in PUNCTUATION_OR_SPACE causes issues with URLs that have extensions like .png functioning correctly.

I've submitted a PR to address this, and I would appreciate it if you could review it to ensure that the recognition works as intended.

#4430

**Comment by intrnl** [comment] 2023-09-26 01:37
is there another way we could do autolinks? much in the same way as ProseMirror's decorations where the decorations doesn't actually represent actual nodes on the document, just one that happens to decorate the view

https://prosemirror.net/docs/ref/#view.Decorations

**Comment by prestonbrown-me** [comment] 2023-12-07 22:07
https://github.com/facebook/lexical/pull/5275

Relevant update for those waiting on this

**Comment by thorn0** [comment] 2024-03-27 00:50
Can't `PUNCTUATION_OR_SPACE` be made configurable?

**Comment by redstar504** [comment] 2024-06-03 21:28
For anyone struggling with this issue, I wrote a very simple replacement plugin.  I urgently needed a solution to unblock my project. Since I wanted to take a different approach, it seemed easier to start from scratch instead of   modifying the existing plugin. Full disclosure, it's my first time releasing an npm package, so I have no idea how it will work for you, but it's worth a shot for those having trouble. The demo is available [here](https://redstar504.github.io/lexical-anchorpoint/). I would be happy for anyone to test it further.

**Comment by MaxPlav** [comment] 2024-06-12 17:08
hi, it should be fixed now https://github.com/facebook/lexical/pull/6146

**Closed** 2024-12-03 06:57 UTC
Labels: good first issue, all-platforms-bug, hyperlinks, contribution-week
