### ISSUE TITLE
Bug: Deleting a line (via `CMD` + `BACKSPACE`) when the range selection is at a decorator node does not work

### ISSUE THREAD

**Issue by nimeshnayaju** [facebook/lexical#6047] opened 2024-05-07 14:40 UTC
Lexical version: 0.14.5

## Steps To Reproduce

1. Add a decorator node (e.g. Poll/Image)
2. Set the selection right at the end of the node. (screencast attached)
3. Attempt to delete the line (via <kbd>Cmd</kbd> + <kbd>Backspace</kbd> on Mac)

I believe this is an unintended side effect of [this PR](https://github.com/facebook/lexical/pull/2813). The PR checks if the anchor node is of type `text` before extending the selection but notice in the screencast, the anchor node is of type `element`, so the selection isn't expanded before the text in selection is removed.

https://github.com/facebook/lexical/assets/35807215/90cf290f-6ff5-4c56-b1ea-be5951c08a0d

**Comment by sheharyarIshfaq** [comment] 2024-08-04 18:46
Hi, I want to work on this, can you please assign it to me

**Comment by etrepum** [comment] 2024-08-05 00:32
It looks like #6160 already fixed this, I can't reproduce

**Closed by etrepum** 2024-08-05 00:32 UTC
Labels: good first issue, mac-bug, contribution-week
