### ISSUE TITLE
Bug: This is a bug where the table width cannot be adjusted after merging cells.

### ISSUE THREAD

**Issue by eleganceJoo** [facebook/lexical#5515] opened 2024-01-19 06:12 UTC
Lexical version: **2024-01-19 playground version**

## Steps To Reproduce

1. Add a table.
2. Merge cells.
3. Adjust the width of the last column.
4. I can't control the screen.

**### Attached is a recorded video.**
## The current behavior
https://github.com/facebook/lexical/assets/157095195/e8b1687e-8e47-408f-8a2d-dd9f45b3c863

**Comment by ivailop7** [comment] 2024-01-19 23:24
This was fixed in here: #5169, but apparently after this merge the issue is still there.

**Comment by ivailop7** [comment] 2024-04-02 23:04
Interestingly I'm not able to reproduce this one anymore

**Comment by ivailop7** [comment] 2024-05-21 22:12
Still reproducible, encountered this one recently.

**Comment by ivailop7** [comment] 2024-05-25 16:08
@AlexanderReznik is looking into this one

**Closed** 2024-05-31 01:07 UTC
Labels: tables
