### ISSUE TITLE
Bug: listening to selection changes via SELECTION_CHANGE_COMMAND doesn't work as expected for custom decorator nodes

### ISSUE THREAD

**Issue by iampava** [facebook/lexical#2754] opened 2022-08-04 06:24 UTC
Lexical version: 0.3.8

## Steps To Reproduce

1. Create a custom Decorator Node with click-selection functionality
2. Create a plugin that listens to `SELECTION_CHANGE_COMMAND` and prints the selection
3. Add the custom Decorator Node in the editor
4. Click on the custom Decorator Node to select it
5. Notice how the result printed by the `SELECTION_CHANGE_COMMAND` listener doesn't refer to the custom node.
6. NOTE: if instead we listen to selection changes via the `<OnChangePlugin>`, things work as expected.

Link to code example: https://codesandbox.io/s/facebook-lexical-selection-bug-1ct727

## The expected behavior

Listening to selections via `editor.registerCommand<void>(SELECTION_CHANGE_COMMAND` should "catch" all selection changes, including custom decorator nodes.

**Comment by thegreatercurve** [comment] 2022-11-24 15:45
Duplicate of #3160

**Closed by thegreatercurve** 2022-11-24 15:45 UTC
