### ISSUE TITLE
Feature: Allow range selections on top-level decorator nodes

### ISSUE THREAD

**Issue by kevinansfield** [facebook/lexical#2883] opened 2022-08-24 10:49 UTC
# Description

I'm investigating Lexical as an alternative to [mobiledoc-kit ](https://github.com/bustle/mobiledoc-kit) as the underlying framework that powers our editor at [Ghost](https://ghost.org). One of the key usability features of our editor is cards entering a "selected" state via the keyboard (equivalent of a card would be a top-level decorator node).

Here's a minimal example of our most basic card interaction with a HR card:

https://user-images.githubusercontent.com/415/186399138-6404166d-bfb1-4d03-a688-5c40ee4af7b5.mp4

In mobiledoc-kit such selections are achievable because every card has a `&zwnj;` character before and after the card's DOM element which can receive a cursor position. We can use the equivalent of an update listener to watch for the cursor being in one of those positions/ranges so we can trigger both cursor normalisation (it's always moved to the trailing zwnj so it's easier to handle delete/backspace keyboard events) and to put the card component into a selected state.

As far as I can tell such behaviour isn't possible in Lexical because there is nowhere for the cursor to be positioned on/around a decorator.

# Alternative solutions

Not sure, maybe there are already hooks that could allow such behaviour?

**Comment by trueadm** [comment] 2022-08-24 11:29
Does https://github.com/facebook/lexical/pull/2884 fix this for you? It seems to literally do what you're asking for (ironically haha).

**Comment by kevinansfield** [comment] 2022-08-24 12:03
@trueadm it looks like it may well do! I'll pull your PR down to play with it and let you know, thank you 🎉

**Comment by kevinansfield** [comment] 2022-08-24 13:46
@trueadm your PR does address the core issue for us 🙂 One question though - is it expected that up/down arrows don't select the HR node? Left/Right does select but Up/Down skips over similar to the previous behaviour.

**Comment by trueadm** [comment] 2022-09-04 00:35
That's expected. The truth is, up/down is hard as the caret's position in respect to the items above and below are hard to anticipate. We'd have to involve a lot of complex operations using getBoundingClientRect and try and work out intersections to make it work – only for it to fail on iOS or Android in all likelihood. So rather than going for the complexity, we just ensure left/right always works, which seems like a good trade-off.

**Comment by kevinansfield** [comment] 2022-09-05 10:04
OK. In that case it sounds like something we'd have implement via overriding the up/down commands 🤔

**Comment by trueadm** [comment] 2022-09-05 10:53
We used a similar approach to having `&zwnj;` back in the day, except we used a zero width character to same effect. The problem is accessibility – it causes screen readers to read out the strange character and was causing us lots of reports from screen reader users that the editor was confusing. You can also roll your own up/down command and do something different, and if you come up with something effective, we'd love to have it in core too :)

**Comment by DaniGuardiola** [comment] 2022-09-12 14:56
How about putting the invisible character in a `span` or `p` with `role="presentational"`? Maybe that would make screen readers ignore it and up and down arrows could work? I feel like missing this interaction hurts usability significantly, so I'd love to see it built :)

**Comment by trueadm** [comment] 2022-09-12 15:55
Bizarrely, display roles seem really buggy when in editing modes on screen readers. I wish browsers had invested more time into the standardization around content editable so we could all address these issues and the caveats around the role certain attributes and elements have inside content editable

**Comment by DaniGuardiola** [comment] 2022-10-11 09:16
@kevinansfield did you end up implementing this? If so, how? up/down commands?

**Comment by kevinansfield** [comment] 2022-10-26 21:55
@DaniGuardiola I was noodling on our up/down arrow behaviour a bit this evening and ended up with this https://github.com/TryGhost/Koenig/pull/390. Probably not 100% yet but initial testing shows it working for our use-cases. I'll add some tests tomorrow and merge then it will be testable on our demo at https://koenig.ghost.org

One odd thing I've come across is the built-in Up/Down key handling when there's a node selection [seems to skip a node](https://github.com/facebook/lexical/issues/3270) and puts the caret in an unexpected position.

**Comment by trueadm** [comment] 2022-11-24 16:01
Closing this for now as it's not in scope for core work. Will re-open it in the future if this changes :)

**Closed by trueadm** 2022-11-24 16:01 UTC
Labels: enhancement
