### ISSUE TITLE
Bug: [Playground] Changes to font-size or font-family cause the editor to blur

### ISSUE THREAD

**Issue by lukebreezee** [facebook/lexical#2922] opened 2022-08-31 18:23 UTC
Hello Lexical Team,
Someone may have pointed this out already, but I've been following the functionality of the Lexical playground to create a Lexical wrapper component for my team to reuse. It seems that, in the Lexical Playground, changing font size and font family requires text to be selected. If no text is selected, but the editor is focused, I'd expect changes to font size or font family to affect text that is typed afterward. What happens instead is that the editor blurs i.e. unfocuses.

I would provide screenshots, it's just a bit difficult to capture, but please let me know if you need more information than what I have provided.

Lexical version: 0.3.11

## Steps To Reproduce

1. (In the playground) Make sure the browser is focused on the editor and no text is selected
2. Try to change font size or font family

Link to code example: playground.lexical.dev

## The current behavior
The editor blurs on font size or font family change when no text is selected

## The expected behavior
I was wanting the changes to font size and font family in the editor to affect text that is typed afterward and keep the browser focused on the editor input

**Comment by trueadm** [comment] 2022-09-04 00:33
This is because font-size and font-family aren't native controls of selection right now. Only the format is – as this is something that is constrained in scope and easy to manage. Font-size and font-family are completely variable, so it makes it hard to map to selection.

Our initial thought was that both these styling options would be rarely used – as most folks would prefer themes define those properties, however, we could maybe map some of the font-sizes to selection. Font family would require us to add an entirely new property to selection.

**Comment by trueadm** [comment] 2022-11-24 16:02
Closing for now as I feel this isn't something we want to introduce the complexity in core for

**Comment by TheSwilliam** [comment] 2023-01-10 20:50
Hi @trueadm,

I am new to lexical and have faced this issue. Would you mind providing a code example of a work around so we can achieve the necessary behavior? 

I much appreciate all the hard work on this!

**Comment by trueadm** [comment] 2023-01-10 21:03
Ah I reread the original issue. Let me look into this later this week

**Comment by thegreatercurve** [comment] 2023-03-03 23:02
This has been recently fixed with some changes to selection to support better font-size and font-family usage with selection. I've confirmed in the playground that this is no longer reproducible.

**Closed by thegreatercurve** 2023-03-03 23:02 UTC
