### ISSUE TITLE
Feature: LexicalComposer initialState should accept SerializedEditorState

### ISSUE THREAD

**Issue by etrepum** [facebook/lexical#6039] opened 2024-05-06 15:41 UTC
Currently the `initialState` prop accepts an `InitialEditorStateType`

```typescript
export type InitialEditorStateType =
  | null
  | string
  | EditorState
  | ((editor: LexicalEditor) => void);
```

In a normal root editor situation, it's hard to get an `EditorState`, because you need a `LexicalEditor` to parse one… but it's not entirely uncommon to have already parsed the JSON. I ran into this myself when I started using Lexical and it's come up [on the discord](https://discord.com/channels/953974421008293909/953974421486436393/1236963878206967818).

I would recommend extending the type to:

```typescript
export type InitialEditorStateType =
  | null
  | string
  | SerializedEditorState
  | EditorState
  | ((editor: LexicalEditor) => void);
```

And change the type check in `initializeEditor` from this:

```typescript
    switch (typeof initialEditorState) {
      case 'string': {
        const parsedEditorState = editor.parseEditorState(initialEditorState);
        editor.setEditorState(parsedEditorState, HISTORY_MERGE_OPTIONS);
        break;
      }
      case 'object': {
        editor.setEditorState(initialEditorState, HISTORY_MERGE_OPTIONS);
        break;
      }
      case 'function': {
        editor.update(() => {
          const root = $getRoot();
          if (root.isEmpty()) {
            initialEditorState(editor);
          }
        }, HISTORY_MERGE_OPTIONS);
        break;
      }
    }
```

to something like this:

```typescript
    switch (typeof initialEditorState) {
      case 'string': {
        const parsedEditorState = editor.parseEditorState(initialEditorState);
        editor.setEditorState(parsedEditorState, HISTORY_MERGE_OPTIONS);
        break;
      }
      case 'object': {
        const editorState = initialEditorState instanceof EditorState 
          ? initialEditorState
          : editor.parseEditorState(initialEditorState);
        editor.setEditorState(editorState, HISTORY_MERGE_OPTIONS);
        break;
      }
      case 'function': {
        editor.update(() => {
          const root = $getRoot();
          if (root.isEmpty()) {
            initialEditorState(editor);
          }
        }, HISTORY_MERGE_OPTIONS);
        break;
      }
    }
```

It would be a good opportunity to add a `__DEV__` check to validate the structure of the `serializedEditorState` passed to `parseEditorState` (some people are using JS and TS doesn't help all that much around JSON boundaries since there's any everywhere), such as:

```typescript
invariant(serializedEditorState && typeof serializedEditorState === 'object', 'parseEditorState: missing or invalid serializedEditorState');
if (__DEV__ && typeof serializedEditorState.root !== 'object') {
  if (serializedEditorState.constructor !== Object) {
    invariant(!(serializedEditorState instanceof EditorState), 'parseEditorState: can not parse an already parsed EditorState');
    invariant(false, 'parseEditorState: root missing from serializedEditorState and does not appear to be parsed JSON (instance of %s, not Object). Multiple versions of lexical may be present.', serializedEditorState.constructor.name);
  }
  invariant(false, 'parseEditorState: root missing from serializedEditorState, does not appear to be the result of editorState.toJSON()');
}
```

**Comment by StyleT** [comment] 2024-05-06 19:59
Closed as duplicate of #3732 :P Sorry mate

**Closed by StyleT** 2024-05-06 19:59 UTC
Labels: enhancement
